class_name PlanetaryWorld
extends Node3D

## Solar system scaffold:
##
##   World (Node3D, this script)
##     └── Star               — fixed at the origin
##           ├── SunLight     — DirectionalLight3D pointing toward the planet
##           └── SunVisual    — unshaded glowing sphere (always visible)
##     └── PlanetSystem       — Node3D that ORBITS the star
##           ├── Planet       — terrain + chunk octree
##           ├── Atmosphere   — inverted sphere shell shader
##           └── Water        — ocean sphere at sea level
##           (the FlightPlayer is reparented to this node by main.gd so it
##            travels with the planet through space)
##
## Two motions drive the day/night + season cycle:
##
##   * Orbital motion — PlanetSystem revolves around Star at `orbit_radius`
##     once every `orbit_period_sec`. This is the "year".
##   * Axial rotation — PlanetSystem spins on `axis_local` once every
##     `day_length_sec`. This is the "day".
##
## The axial tilt (`axial_tilt_deg`) is the angle between the spin axis and the
## orbital plane normal. Combined with the orbit, it drives the seasons: in one
## half of the year a hemisphere gets more sun, in the other half less.
##
## Floating-point note: at `orbit_radius` ~ 60 km the world positions stay well
## inside single-precision float comfort. For real-AU-scale orbits you'd want
## a floating-origin system; that's out of scope here.

@export var planet_radius     : float = 4000.0
@export var atmosphere_radius : float = 4520.0
@export var cloud_inner_radius : float = 4180.0   # bottom of the volumetric cloud deck
@export var cloud_outer_radius : float = 4420.0   # top of the deck (inside the atmosphere shell)
@export var sea_level_offset  : float = -200.0    # SEA 200 m below planet_radius. Mean continent height with the -0.55 bias / 380 multiplier is around -209 m, so the previous offset of 0 left the average surface well under water — only noise>0.32 areas surfaced. -200 puts sea AT roughly the mean surface so ~50% of the planet is land, dropping below for ocean basins and rising into continents/mountains above.
@export var world_seed        : int   = 1337

@export var orbit_radius      : float = 1800000.0 # sun is far away (≈75× planet radius) — scaled with planet
@export var orbit_period_sec  : float = 600.0     # one full revolution
@export var day_length_sec    : float = 480.0     # one full axial rotation (slower → shadows don't shimmer)
@export var axial_tilt_deg    : float = 23.5      # like Earth
@export var sun_radius        : float = 78000.0   # scaled with orbit_radius so the disc keeps its apparent size (still clearly visible + glows)
@export var sun_color         : Color = Color(1.0, 0.93, 0.78)
@export var sun_energy        : float = 0.55   # directional light only — the bright sun DISC is the emission_energy_multiplier on sun_visual, which is unaffected by this and keeps its full HDR bloom

# Moon — a rocky satellite orbiting the planet. Voxel-LOD `Planet` with its
# own `CraterDensity` so the surface has actual impact craters generated by
# the mesher (not just a shader trick). Smaller `max_lod` and `base_chunk_size`
# since the moon is much smaller than the planet.
@export var moon_radius          : float = 3300.0
@export var moon_orbit_radius    : float = 450000.0   # far out (≈19× planet radius); at this distance it reads as a small disc like the real Moon
@export var moon_orbit_period_sec: float = 200.0
@export var moon_inclination_deg : float = 8.0
@export var moon_spin_period_sec : float = 200.0    # tidally locked by default (same as orbit)
@export var moon_seed            : int   = 42
@export var moon_crater_count    : int   = 260
@export var moon_max_lod         : int   = 5
@export var moon_base_chunk_size : float = 24.0

# Floating-origin threshold: when the active camera drifts more than this far
# from world (0,0,0), shift the WHOLE scene back so the camera ends up at the
# origin again. Lets us crank `orbit_radius` to anything (AU-scale) without
# losing float precision in chunk coordinates. Set <= 0 to disable.
@export var floating_origin_threshold : float = 4000.0

var star          : Node3D
var sun_light     : DirectionalLight3D
var sun_visual    : MeshInstance3D
var planet_system : Node3D
var planet        : Planet
var atmosphere    : MeshInstance3D
var water         : MeshInstance3D
var clouds        : MeshInstance3D
var atmosphere_mat: ShaderMaterial
var water_mat     : ShaderMaterial
var cloud_mat     : ShaderMaterial
var terrain_mat   : ShaderMaterial
var world_env     : WorldEnvironment
var moon_system   : Node3D
var moon          : Planet
var moon_density  : CraterDensity
var moon_material : ShaderMaterial
var _moon_orbit_phase : float = 0.0
var _moon_spin_phase  : float = 0.0

var _orbit_phase  : float = 0.0
var _spin_phase   : float = 0.0
# Spin axis in local PlanetSystem coords — tilted by `axial_tilt_deg` around
# the orbital plane normal. The PlanetSystem rotates around this axis.
var _spin_axis_local : Vector3 = Vector3.UP
# Tracks whether the camera was last reported as below sea level — used to
# avoid toggling fog state every frame unnecessarily.
var _camera_underwater : bool = false

# Floating-origin offset. Conceptually:
#   rendered_world_position = absolute_position - origin_offset
# Tracked as three GDScript `float`s (which are 64-bit doubles) — not a
# Vector3 — because Godot 4's Vector3 stores components as 32-bit floats,
# which would lose precision at AU-scale orbits. We only collapse to a
# Vector3 AFTER subtracting the absolute coordinate, when the result is
# small and fits in 32-bit float comfortably.
var _origin_offset_x : float = 0.0
var _origin_offset_y : float = 0.0
var _origin_offset_z : float = 0.0


func world_origin_offset() -> Vector3:
	return Vector3(_origin_offset_x, _origin_offset_y, _origin_offset_z)


# Show/hide the volumetric cloud deck. Returns the new visibility state.
func toggle_clouds() -> bool:
	if clouds:
		clouds.visible = not clouds.visible
		return clouds.visible
	return false


func _ready() -> void:
	_normalize_shell_radii()
	_build_environment()
	_build_star()
	_build_planet_system()
	_build_moon()
	_apply_initial_transforms()


# Make `planet_radius` the single size knob. The terrain height budget, ocean
# depth and atmospheric thickness in this project are ABSOLUTE metres (see
# density.rs / density.gd — feature heights don't scale with radius), so the
# atmosphere and cloud shells are planet_radius + a fixed offset. Changing
# planet_radius then grows the sphere while keeping the same terrain/sea/sky
# band, instead of leaving the shells stuck at their 4000 m-planet defaults.
func _normalize_shell_radii() -> void:
	# Thicker atmosphere band — the old 520 m shell looked pancake-flat against
	# a 24 km planet (≈2% of the radius). Earth's atmosphere is closer to ~10%
	# of its radius before becoming optically thin; pushing to 2400 m + clouds
	# between 900–1900 m gives the horizon a proper soft fall-off and keeps
	# clouds visibly suspended above terrain (max terrain peaks ≈ +1576 m).
	atmosphere_radius  = planet_radius + 2400.0
	cloud_inner_radius = planet_radius + 900.0
	cloud_outer_radius = planet_radius + 1900.0


func _process(delta: float) -> void:
	_orbit_phase = fposmod(_orbit_phase + delta * TAU / max(orbit_period_sec, 0.001), TAU)
	_spin_phase  = fposmod(_spin_phase  + delta * TAU / max(day_length_sec,  0.001), TAU)
	_moon_orbit_phase = fposmod(_moon_orbit_phase + delta * TAU / max(moon_orbit_period_sec, 0.001), TAU)
	_moon_spin_phase  = fposmod(_moon_spin_phase  + delta * TAU / max(moon_spin_period_sec,  0.001), TAU)
	_maybe_shift_origin()
	_update_transforms()
	_update_underwater()


# Floating-origin recentre. When the active camera drifts past
# `floating_origin_threshold` from world (0,0,0), bump `world_origin_offset`
# by the camera's current world position. `_update_transforms` then
# recomputes the star + planet_system positions using the new offset, which
# moves the planet_system back toward the origin (and the camera with it,
# since the camera is a child of planet_system). Result: camera ≈ (0,0,0)
# again, every absolute relative position preserved, no visible jump.
func _maybe_shift_origin() -> void:
	if floating_origin_threshold <= 0.0:
		return
	var cam := get_viewport().get_camera_3d()
	if cam == null:
		return
	var d2 := cam.global_position.length_squared()
	if d2 < floating_origin_threshold * floating_origin_threshold:
		return
	# Cast through GDScript `float` (64-bit) for accumulation precision.
	_origin_offset_x += float(cam.global_position.x)
	_origin_offset_y += float(cam.global_position.y)
	_origin_offset_z += float(cam.global_position.z)


# Toggle the WorldEnvironment fog to an underwater tint when the camera's
# distance from the planet center drops below sea level. Cheap to evaluate
# every frame; the actual `env.fog_enabled` toggle only flips when state
# changes.
func _update_underwater() -> void:
	if world_env == null:
		return
	var cam := get_viewport().get_camera_3d()
	if cam == null:
		return
	var sea_r := planet_radius + sea_level_offset
	var r := cam.global_position.distance_to(planet_system.global_position)
	var below := r < sea_r
	if below == _camera_underwater:
		return
	_camera_underwater = below
	var env := world_env.environment
	if env == null:
		return
	if below:
		env.fog_enabled = true
		env.fog_mode = Environment.FOG_MODE_EXPONENTIAL
		env.fog_light_color = Color(0.05, 0.18, 0.28)
		env.fog_light_energy = 0.85
		env.fog_density = 0.045
		env.fog_aerial_perspective = 0.0
		env.fog_sun_scatter = 0.0
		env.adjustment_saturation = 0.85
	else:
		env.fog_enabled = false
		env.adjustment_saturation = 1.1


# ────────────────────────────────────────────────────────────────────────────

func _build_environment() -> void:
	var env := Environment.new()
	env.background_mode = Environment.BG_SKY
	var sky := Sky.new()
	var sky_mat := ProceduralSkyMaterial.new()
	sky_mat.sky_top_color    = Color(0.004, 0.005, 0.012)
	sky_mat.sky_horizon_color= Color(0.01, 0.012, 0.022)
	sky_mat.sky_curve        = 0.4
	sky_mat.ground_bottom_color  = Color(0.0, 0.0, 0.0)
	sky_mat.ground_horizon_color = Color(0.0, 0.0, 0.0)
	sky_mat.sun_angle_max    = 0.3
	sky_mat.energy_multiplier = 0.4
	sky.sky_material = sky_mat
	env.sky = sky
	env.tonemap_mode = Environment.TONE_MAPPER_ACES
	# Lower exposure dims the entire HDR frame BEFORE tone-mapping, so the
	# atmosphere/clouds/terrain darken proportionally. The sun disc is at
	# emission ≈18 — still vastly above the glow HDR threshold (1.5) post-exposure,
	# so its bloom/corona is preserved while the rest of the scene calms down.
	env.tonemap_exposure = 0.7
	env.tonemap_white = 6.0
	env.ambient_light_source = Environment.AMBIENT_SOURCE_SKY
	env.ambient_light_sky_contribution = 0.35
	env.ambient_light_energy = 0.10   # near-zero base; deep-space scenes should have very little fill light
	env.glow_enabled = true
	env.glow_intensity = 1.1
	env.glow_strength = 1.2
	env.glow_bloom = 0.3
	# Only the very bright (HDR) sun disc blooms, and it blooms across several
	# octaves so it reads as a big soft glow/corona rather than a hard sphere.
	# Raised so ONLY the very bright HDR sun disc (emission ≈16) blooms into the
	# soft corona we want — the dimmer blue atmosphere shell stays below the
	# threshold and no longer blooms, which is what made the sky read too bright.
	env.glow_hdr_threshold = 1.5
	env.glow_hdr_scale = 2.0
	env.set_glow_level(2, 1.0)
	env.set_glow_level(3, 1.0)
	env.set_glow_level(4, 1.0)
	env.set_glow_level(5, 0.6)
	env.adjustment_enabled = true
	env.adjustment_brightness = 0.85   # final knock-down: keeps the sun glow but pulls the rest of the frame toward proper deep-space contrast
	env.adjustment_contrast = 1.08
	env.adjustment_saturation = 1.1
	world_env = WorldEnvironment.new()
	world_env.environment = env
	add_child(world_env)


func _build_star() -> void:
	star = Node3D.new()
	star.name = "Star"
	add_child(star)
	# Place the star at world origin. Planet orbits around (0,0,0).
	star.global_position = Vector3.ZERO

	sun_light = DirectionalLight3D.new()
	sun_light.name = "SunLight"
	sun_light.light_color = sun_color
	sun_light.light_energy = sun_energy
	sun_light.shadow_enabled = true
	sun_light.directional_shadow_mode = DirectionalLight3D.SHADOW_PARALLEL_4_SPLITS
	# Bigger max-distance so the shadow frustum covers more of the planet
	# without snapping pixel boundaries as the camera moves.
	sun_light.directional_shadow_max_distance = 2400.0
	sun_light.directional_shadow_split_1 = 0.06
	sun_light.directional_shadow_split_2 = 0.18
	sun_light.directional_shadow_split_3 = 0.45
	sun_light.directional_shadow_blend_splits = true
	# Planetary geometry needs a much bigger bias than the Godot default to
	# avoid shadow acne / self-shadow flicker on terrain that spans hundreds
	# of metres per chunk.
	sun_light.shadow_bias = 0.6
	sun_light.shadow_normal_bias = 3.0
	sun_light.shadow_opacity = 0.92
	star.add_child(sun_light)

	sun_visual = MeshInstance3D.new()
	sun_visual.name = "SunVisual"
	var sm := SphereMesh.new()
	sm.radius = sun_radius
	sm.height = sun_radius * 2.0
	sm.radial_segments = 64
	sm.rings = 32
	sun_visual.mesh = sm
	sun_visual.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	sun_visual.gi_mode = GeometryInstance3D.GI_MODE_DISABLED
	sun_visual.extra_cull_margin = sun_radius
	var sun_m := StandardMaterial3D.new()
	sun_m.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	sun_m.albedo_color = sun_color
	sun_m.emission_enabled = true
	sun_m.emission = sun_color
	sun_m.emission_energy_multiplier = 18.0
	sun_visual.material_override = sun_m
	star.add_child(sun_visual)


func _build_planet_system() -> void:
	planet_system = Node3D.new()
	planet_system.name = "PlanetSystem"
	add_child(planet_system)

	# ── Planet ─────────────────────────────────────────────────────────────
	planet = Planet.new()
	planet.planet_radius = planet_radius
	planet.world_seed = world_seed
	planet.base_chunk_size = 48.0
	# +1 level vs. before: the planet is now ~2× the radius, so the coarsest
	# octree cells cover 2× the area each — without this the far/orbital view
	# would spawn ~4× as many top-level chunks. Finest detail is unchanged
	# (base_chunk_size is the same), this only adds a coarser root tier.
	planet.max_lod = 9   # +2 vs 8 km planet (now ~24 km): each step doubles root cell size, so this keeps the root-cell COUNT the same as the planet grows; finest LOD (base_chunk_size) is unchanged
	# 12 cells/axis (was 16) gives a 60% triangle-budget cut at every LOD —
	# the root chunks were emitting tens of thousands of triangles each
	# because the detail noise was aliasing across their 256 m voxels into
	# phantom iso-surface crossings. Going from 16 to 12 (still even, which
	# the boundary-resampling math requires) drops cell count from 4096 to
	# 1728 per chunk and brings the in-space view down by several × without
	# noticeably blurring the surface at close LODs.
	planet.voxel_resolution = 12
	# Lower lod_factor → coarser sooner → far fewer chunks at orbital distance
	# (was 2.4 → ~1236 chunks; 1.8 ≈ 0.42× that). Big CPU/framerate win, and the
	# orbital view doesn't need that much near-detail.
	# Bumped back up (was 1.8). 1.8 put LOD boundaries right at the camera's
	# subdivide radius, so a small camera move could flip a neighbour two LODs
	# in one frame — the inline 2:1 check then has to cascade-split during the
	# same tick the old chunk is being freed, and the brief window where the
	# transition-mask re-mesh hasn't applied yet is exactly the crack. A wider
	# subdivide radius pushes the boundary further out so swaps happen earlier
	# and with more spatial cushion.
	planet.lod_factor = 2.2
	planet.collision_lod_max = 1
	planet.max_new_chunks_per_tick = 16
	planet.sea_level_offset = sea_level_offset
	planet.name = "Planet"
	terrain_mat = ShaderMaterial.new()
	terrain_mat.shader = load("res://shaders/terrain.gdshader")
	terrain_mat.set_shader_parameter("planet_center", Vector3.ZERO)
	terrain_mat.set_shader_parameter("planet_radius", planet_radius)
	terrain_mat.set_shader_parameter("polar_axis", Vector3.UP)
	terrain_mat.set_shader_parameter("snow_altitude", planet_radius * 0.05)
	terrain_mat.set_shader_parameter("polar_cap_latitude", 0.82)
	terrain_mat.set_shader_parameter("polar_cap_fade", 0.10)
	terrain_mat.set_shader_parameter("beach_altitude", 8.0)
	terrain_mat.set_shader_parameter("beach_fade", 14.0)
	planet.terrain_material = terrain_mat
	planet_system.add_child(planet)

	# ── Atmosphere shell ───────────────────────────────────────────────────
	atmosphere = MeshInstance3D.new()
	atmosphere.name = "Atmosphere"
	var amesh := SphereMesh.new()
	amesh.radius = atmosphere_radius
	amesh.height = atmosphere_radius * 2.0
	amesh.radial_segments = 64
	amesh.rings = 32
	atmosphere.mesh = amesh
	atmosphere.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	atmosphere.gi_mode = GeometryInstance3D.GI_MODE_DISABLED
	atmosphere.extra_cull_margin = atmosphere_radius
	atmosphere_mat = ShaderMaterial.new()
	atmosphere_mat.shader = load("res://shaders/atmosphere.gdshader")
	atmosphere_mat.set_shader_parameter("planet_center", Vector3.ZERO)
	atmosphere_mat.set_shader_parameter("planet_radius", planet_radius)
	atmosphere_mat.set_shader_parameter("atmosphere_radius", atmosphere_radius)
	atmosphere_mat.set_shader_parameter("rayleigh_color", Vector3(0.21, 0.45, 0.95))
	atmosphere_mat.set_shader_parameter("mie_color", Vector3(1.0, 0.85, 0.65))
	# Toned down (was 1.6 / 0.55): the atmosphere halo was overpowering the
	# surface and over-brightening the sky. Lower scattering keeps a believable
	# horizon haze without washing everything out.
	# Bumped (was 0.45 / 0.18): from the ground the atmosphere was almost
	# invisible — the user could see "through" the sky at distant terrain and
	# the boundary at the top of the shell looked like a hard edge against
	# space. 0.85 / 0.30 gives a proper visible blue sky from the ground while
	# the lowered sun_energy (0.55) keeps the surface itself from over-brightening.
	atmosphere_mat.set_shader_parameter("scattering_strength", 0.85)
	atmosphere_mat.set_shader_parameter("mie_strength", 0.30)
	# Concentric transparent shells (water < clouds < atmosphere) share the
	# planet centre, so Godot can't depth-sort them by camera distance and
	# their draw order flips frame-to-frame (the cloud/atmosphere flicker).
	# Pin an explicit order: outer shells draw last, over the inner ones.
	atmosphere_mat.render_priority = 2
	atmosphere.material_override = atmosphere_mat
	planet_system.add_child(atmosphere)

	# ── Water ocean ────────────────────────────────────────────────────────
	water = MeshInstance3D.new()
	water.name = "Water"
	var wmesh := SphereMesh.new()
	var wr := planet_radius + sea_level_offset
	wmesh.radius = wr
	wmesh.height = wr * 2.0
	wmesh.radial_segments = 96
	wmesh.rings = 48
	water.mesh = wmesh
	water.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	water.gi_mode = GeometryInstance3D.GI_MODE_DISABLED
	water.extra_cull_margin = wr
	water_mat = ShaderMaterial.new()
	water_mat.shader = load("res://shaders/water.gdshader")
	water_mat.set_shader_parameter("planet_center", Vector3.ZERO)
	water_mat.set_shader_parameter("planet_radius", planet_radius)
	water_mat.set_shader_parameter("sea_level_offset", sea_level_offset)
	water_mat.render_priority = 0
	water.material_override = water_mat
	planet_system.add_child(water)

	# ── Volumetric cloud deck ───────────────────────────────────────────────
	# Raymarched shell rendered on a sphere at the deck's outer radius. The
	# shader clips the view ray to [cloud_inner, cloud_outer] and marches it,
	# so it works from orbit, inside the deck, or on the ground looking up.
	clouds = MeshInstance3D.new()
	clouds.name = "Clouds"
	var cmesh := SphereMesh.new()
	cmesh.radius = cloud_outer_radius
	cmesh.height = cloud_outer_radius * 2.0
	cmesh.radial_segments = 64
	cmesh.rings = 32
	clouds.mesh = cmesh
	clouds.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	clouds.gi_mode = GeometryInstance3D.GI_MODE_DISABLED
	clouds.extra_cull_margin = cloud_outer_radius
	cloud_mat = ShaderMaterial.new()
	cloud_mat.shader = load("res://shaders/clouds.gdshader")
	cloud_mat.set_shader_parameter("planet_center", Vector3.ZERO)
	cloud_mat.set_shader_parameter("planet_radius", planet_radius)
	cloud_mat.set_shader_parameter("cloud_inner", cloud_inner_radius)
	cloud_mat.set_shader_parameter("cloud_outer", cloud_outer_radius)
	cloud_mat.render_priority = 1
	clouds.material_override = cloud_mat
	planet_system.add_child(clouds)


func _build_moon() -> void:
	moon_system = Node3D.new()
	moon_system.name = "MoonSystem"
	add_child(moon_system)

	# Crater density — distinct seed so it doesn't pattern-match the planet's
	# noise. The CraterDensity samples a bowl-shaped profile for each impact
	# plus dust fbm for micro-relief.
	moon_density = CraterDensity.new(moon_radius, moon_seed, moon_crater_count)

	# Moon material — gray, mare/highland blend, no biomes.
	moon_material = ShaderMaterial.new()
	moon_material.shader = load("res://shaders/moon_terrain.gdshader")
	moon_material.set_shader_parameter("moon_radius", moon_radius)

	# Spawn the moon as a full LOD `Planet`. Inject the crater density BEFORE
	# add_child so Planet._ready() skips its default DensityField creation.
	moon = Planet.new()
	moon.name = "Moon"
	moon.planet_radius        = moon_radius
	moon.world_seed           = moon_seed
	moon.base_chunk_size      = moon_base_chunk_size
	moon.max_lod              = moon_max_lod
	moon.voxel_resolution     = 12
	moon.lod_factor           = 2.4
	moon.collision_lod_max    = 1
	moon.scatter_lod_max      = -1     # disable scatter (no grass / rocks on the moon)
	moon.sea_level_offset     = 0.0    # no ocean → no submersion test
	moon.terrain_material     = moon_material
	moon.set_density(moon_density)
	moon_system.add_child(moon)


func _apply_initial_transforms() -> void:
	# Spin axis: orbital-plane normal is +Y. Tilt by axial_tilt_deg around +X.
	_spin_axis_local = Basis(Vector3.RIGHT, deg_to_rad(axial_tilt_deg)) * Vector3.UP
	# The terrain shader's polar_axis is in OBJECT space — constant for the
	# life of the planet (it doesn't change as we orbit or spin).
	terrain_mat.set_shader_parameter("polar_axis", _spin_axis_local.normalized())
	# Hand the same axis to the rock-scatter material so its biome math
	# (latitude, polar caps, beach altitude) matches the terrain underneath.
	planet.set_scatter_axis(_spin_axis_local)
	# Water uses polar_axis as a stable reference for its tangent-frame
	# construction (the gradient sample directions on the sphere). Without
	# it the shader falls back to a view-dependent seed and seams across the
	# poles. Same constant object-space vector as terrain/rocks.
	water_mat.set_shader_parameter("polar_axis", _spin_axis_local.normalized())
	_update_transforms()


func absolute_planet_x() -> float:
	return orbit_radius * cos(_orbit_phase)


func absolute_planet_z() -> float:
	return orbit_radius * sin(_orbit_phase)


func _update_transforms() -> void:
	# Compute the absolute (cosmic-frame) planet position in 64-bit doubles,
	# then subtract the (also 64-bit) origin offset BEFORE collapsing to a
	# 32-bit-component Vector3. The subtraction cancels the huge AU-scale
	# magnitudes, leaving a small value that fits in float comfortably.
	var ax := absolute_planet_x() - _origin_offset_x
	var ay := 0.0 - _origin_offset_y
	var az := absolute_planet_z() - _origin_offset_z
	planet_system.global_position = Vector3(ax, ay, az)
	star.global_position = Vector3(-_origin_offset_x, -_origin_offset_y, -_origin_offset_z)

	# Axial rotation — independent of position, so unaffected by the offset.
	planet_system.transform.basis = Basis(_spin_axis_local.normalized(), _spin_phase)

	# Sun light: directional light points from the sun toward the planet. The
	# direction is just the unit vector between them, which is offset-invariant.
	var sun_to_planet := (planet_system.global_position - star.global_position).normalized()
	sun_light.look_at(star.global_position + sun_to_planet * 100.0, Vector3.UP)

	# Atmosphere & water shaders need world-space sun direction and planet
	# center. Both update to whatever the current floating-origin frame is.
	atmosphere_mat.set_shader_parameter("sun_direction", sun_to_planet)
	water_mat.set_shader_parameter("sun_direction", sun_to_planet)
	atmosphere_mat.set_shader_parameter("planet_center", planet_system.global_position)
	water_mat.set_shader_parameter("planet_center", planet_system.global_position)
	if cloud_mat:
		cloud_mat.set_shader_parameter("sun_direction", sun_to_planet)
		cloud_mat.set_shader_parameter("planet_center", planet_system.global_position)
		# Inverse of the planet's spin rotation. The cloud shader rotates the
		# world-space sample position by this to get planet-LOCAL coords, so
		# the noise pattern stays locked to the surface as the planet spins
		# instead of whipping across the sky at the spin rate.
		cloud_mat.set_shader_parameter("planet_basis_inv", planet_system.transform.basis.inverse())

	# Moon — orbits the planet at moon_orbit_radius, inclined out of the
	# orbital plane by moon_inclination_deg. Computed in doubles so the
	# (planet_abs + moon_relative - offset) subtraction holds precision.
	var inc := deg_to_rad(moon_inclination_deg)
	var mx := absolute_planet_x() + moon_orbit_radius * cos(_moon_orbit_phase) - _origin_offset_x
	var my := 0.0 + moon_orbit_radius * sin(_moon_orbit_phase) * sin(inc) - _origin_offset_y
	var mz := absolute_planet_z() + moon_orbit_radius * sin(_moon_orbit_phase) * cos(inc) - _origin_offset_z
	moon_system.global_position = Vector3(mx, my, mz)
	moon.transform.basis = Basis(Vector3.UP, _moon_spin_phase)
