class_name PlanetaryWorld
extends Node3D

## Solar system scaffold:
##
##   World (Node3D, this script)
##     └── Star               — fixed at the origin
##           ├── SunLight     — DirectionalLight3D pointing toward the planet
##           └── SunVisual    — unshaded glowing sphere (always visible)
##     └── PlanetSystem       — Node3D that ORBITS the star
##           ├── Planet       — terrain + chunk octree
##           ├── Atmosphere   — inverted sphere shell shader
##           └── Water        — ocean sphere at sea level
##           (the FlightPlayer is reparented to this node by main.gd so it
##            travels with the planet through space)
##
## Two motions drive the day/night + season cycle:
##
##   * Orbital motion — PlanetSystem revolves around Star at `orbit_radius`
##     once every `orbit_period_sec`. This is the "year".
##   * Axial rotation — PlanetSystem spins on `axis_local` once every
##     `day_length_sec`. This is the "day".
##
## The axial tilt (`axial_tilt_deg`) is the angle between the spin axis and the
## orbital plane normal. Combined with the orbit, it drives the seasons: in one
## half of the year a hemisphere gets more sun, in the other half less.
##
## Floating-point note: at `orbit_radius` ~ 60 km the world positions stay well
## inside single-precision float comfort. For real-AU-scale orbits you'd want
## a floating-origin system; that's out of scope here.

# The single size knob. main.gd (the entry scene) sets this to 24000 at runtime; the
# default matches so a standalone/editor World isn't a different scale. The Rust
# density (settlements, erosion) only activate above ~10000, so this MUST stay large.
# The atmosphere/cloud radii below are DERIVED from this in _normalize_shell_radii —
# their literals here are placeholders that _ready overwrites.
@export var planet_radius     : float = 24000.0
@export var atmosphere_radius : float = 4520.0
@export var cloud_inner_radius : float = 4180.0   # bottom of the volumetric cloud deck (derived in _ready)
@export var cloud_outer_radius : float = 4420.0   # top of the deck (inside the atmosphere shell) (derived in _ready)
@export var sea_level_offset  : float = -200.0    # SEA 200 m below planet_radius. Mean continent height with the -0.55 bias / 380 multiplier is around -209 m, so the previous offset of 0 left the average surface well under water — only noise>0.32 areas surfaced. -200 puts sea AT roughly the mean surface so ~50% of the planet is land, dropping below for ocean basins and rising into continents/mountains above.
@export var world_seed        : int   = 1337

@export var orbit_radius      : float = 1800000.0 # sun is far away (≈75× planet radius) — scaled with planet
@export var orbit_period_sec  : float = 24000.0   # one full revolution = one "year". MUST be ≫ day_length or the
												  # orbit whips the sun around faster than the planet spins (the old
												  # 600 s made a year ≈ a day). 24000 s ≈ 20 in-game days per year.
@export var day_length_sec    : float = 1200.0    # one full axial rotation = ~20 min day/night (was 480 = 8 min, too fast)
@export var axial_tilt_deg    : float = 23.5      # like Earth
@export var sun_radius        : float = 78000.0   # scaled with orbit_radius so the disc keeps its apparent size (still clearly visible + glows)
@export var sun_color         : Color = Color(1.0, 0.93, 0.78)
@export var sun_energy        : float = 1.35   # directional light only (lights the day-side terrain). Raised to bring terrain up after removing glow_bloom's wash — done via DIRECT light, not exposure, so it brightens the surface without feeding more into the sun's bloom. The sun DISC brightness is the emission multiplier on sun_visual, independent of this

# Moon — a rocky satellite orbiting the planet. Voxel-LOD `Planet` with its
# own `CraterDensity` so the surface has actual impact craters generated by
# the mesher (not just a shader trick). Smaller `max_lod` and `base_chunk_size`
# since the moon is much smaller than the planet.
@export var moon_radius          : float = 3300.0
@export var moon_orbit_radius    : float = 450000.0   # far out (≈19× planet radius); at this distance it reads as a small disc like the real Moon
@export var moon_orbit_period_sec: float = 4800.0   # ~4 in-game days per lunar orbit (was 200 = zipped across the sky)
@export var moon_inclination_deg : float = 8.0
@export var moon_spin_period_sec : float = 4800.0   # tidally locked by default (same as orbit)
@export var moon_seed            : int   = 42
@export var moon_crater_count    : int   = 260
@export var moon_max_lod         : int   = 5
@export var moon_base_chunk_size : float = 24.0

# Floating-origin threshold: when the active camera drifts more than this far
# from world (0,0,0), shift the WHOLE scene back so the camera ends up at the
# origin again. Lets us crank `orbit_radius` to anything (AU-scale) without
# losing float precision in chunk coordinates. Set <= 0 to disable.
@export var floating_origin_threshold : float = 4000.0

var star          : Node3D
var sun_light     : DirectionalLight3D
var sun_visual    : MeshInstance3D
var planet_system : Node3D
var planet        : Planet
# City pad centres in the planet's LOCAL frame (same `centers` handed to the
# settlement builder). Cached so the camera-jump key can fly straight to a town.
var settlement_centers : PackedVector3Array = PackedVector3Array()
var atmosphere    : MeshInstance3D
var water         : MeshInstance3D
var clouds        : MeshInstance3D
var atmosphere_mat: ShaderMaterial
var water_mat     : ShaderMaterial
var cloud_mat     : ShaderMaterial
var terrain_mat   : ShaderMaterial
var world_env     : WorldEnvironment
var moon_system   : Node3D
var moon          : Planet
var moon_density  : CraterDensity
var moon_material : ShaderMaterial
var _moon_orbit_phase : float = 0.0
var _moon_spin_phase  : float = 0.0

var _orbit_phase  : float = 0.0
var _spin_phase   : float = 0.0
# Spin axis in local PlanetSystem coords — tilted by `axial_tilt_deg` around
# the orbital plane normal. The PlanetSystem rotates around this axis.
var _spin_axis_local : Vector3 = Vector3.UP
# Tracks whether the camera was last reported as below sea level — used to
# avoid toggling fog state every frame unnecessarily.
var _camera_underwater : bool = false

# Floating-origin offset. Conceptually:
#   rendered_world_position = absolute_position - origin_offset
# Tracked as three GDScript `float`s (which are 64-bit doubles) — not a
# Vector3 — because Godot 4's Vector3 stores components as 32-bit floats,
# which would lose precision at AU-scale orbits. We only collapse to a
# Vector3 AFTER subtracting the absolute coordinate, when the result is
# small and fits in 32-bit float comfortably.
var _origin_offset_x : float = 0.0
var _origin_offset_y : float = 0.0
var _origin_offset_z : float = 0.0


func world_origin_offset() -> Vector3:
	return Vector3(_origin_offset_x, _origin_offset_y, _origin_offset_z)


# Show/hide the volumetric cloud deck. Returns the new visibility state.
func toggle_clouds() -> bool:
	if clouds:
		clouds.visible = not clouds.visible
		return clouds.visible
	return false


func _ready() -> void:
	_normalize_shell_radii()
	_build_environment()
	_build_star()
	_build_planet_system()
	_build_moon()
	_apply_initial_transforms()


# Make `planet_radius` the single size knob. The terrain height budget, ocean
# depth and atmospheric thickness in this project are ABSOLUTE metres (see
# density.rs / density.gd — feature heights don't scale with radius), so the
# atmosphere and cloud shells are planet_radius + a fixed offset. Changing
# planet_radius then grows the sphere while keeping the same terrain/sea/sky
# band, instead of leaving the shells stuck at their 4000 m-planet defaults.
func _normalize_shell_radii() -> void:
	# Thicker atmosphere band — the old 520 m shell looked pancake-flat against
	# a 24 km planet (≈2% of the radius). Earth's atmosphere is closer to ~10%
	# of its radius before becoming optically thin; pushing to 2400 m + clouds
	# between 900–1900 m gives the horizon a proper soft fall-off and keeps
	# clouds visibly suspended above terrain (max terrain peaks ≈ +1576 m).
	# Atmosphere must ENCLOSE the cloud deck (top below) — otherwise the part of
	# the deck poking above the shell has no haze over it and shows a hard line
	# where the atmosphere stops. Cloud top is +2800, so +3000 covers it.
	atmosphere_radius  = planet_radius + 3000.0
	# Cloud deck sits ABOVE the terrain peaks (real max ≈ +1576 m) so it reads as a
	# continuous deck rather than being cut/clipped by every mountain that pokes
	# through it — top at +1800 clears the peaks by ~220 m. The original "clouds
	# float above the atmosphere" problem is fixed on the ATMOSPHERE side instead:
	# the shader's vertical density falloff was softened (exp(-h*3) not *5) so the
	# visible blue haze now extends up to ~+2000–2400 m and encloses this deck,
	# instead of fading out by ~1500 m and leaving the clouds in clear air.
	cloud_inner_radius = planet_radius + 500.0
	cloud_outer_radius = planet_radius + 1800.0


func _process(delta: float) -> void:
	_orbit_phase = fposmod(_orbit_phase + delta * TAU / max(orbit_period_sec, 0.001), TAU)
	_spin_phase  = fposmod(_spin_phase  + delta * TAU / max(day_length_sec,  0.001), TAU)
	_moon_orbit_phase = fposmod(_moon_orbit_phase + delta * TAU / max(moon_orbit_period_sec, 0.001), TAU)
	_moon_spin_phase  = fposmod(_moon_spin_phase  + delta * TAU / max(moon_spin_period_sec,  0.001), TAU)
	_maybe_shift_origin()
	_update_transforms()
	_update_underwater()
	_update_cloud_quality(delta)


# ── Cloud quality auto-LOD ────────────────────────────────────────────────────
# The volumetric deck is the single most expensive draw (a full-screen raymarch).
# Rather than a fixed cost, drive the shader's `quality` uniform from the actual
# frame rate: sag below the floor → step the march budget down (to ~half cost);
# comfortable headroom → step it back up. Asymmetric steps + a half-second cadence
# give hysteresis so it settles instead of oscillating.
const CLOUD_Q_MIN := 0.45
const CLOUD_Q_FPS_LOW := 30.0    # below this, degrade
const CLOUD_Q_FPS_HIGH := 50.0   # above this, restore
var _cloud_quality : float = 1.0
var _cloud_q_timer : float = 0.0

func _update_cloud_quality(delta: float) -> void:
	if cloud_mat == null or clouds == null or not clouds.visible:
		return
	_cloud_q_timer += delta
	if _cloud_q_timer < 0.5:
		return
	_cloud_q_timer = 0.0
	var fps := Engine.get_frames_per_second()
	var q := _cloud_quality
	if fps < CLOUD_Q_FPS_LOW:
		q = maxf(q - 0.1, CLOUD_Q_MIN)
	elif fps > CLOUD_Q_FPS_HIGH:
		q = minf(q + 0.05, 1.0)
	if absf(q - _cloud_quality) > 0.001:
		_cloud_quality = q
		cloud_mat.set_shader_parameter("quality", q)


# Floating-origin recentre. When the active camera drifts past
# `floating_origin_threshold` from world (0,0,0), bump `world_origin_offset`
# by the camera's current world position. `_update_transforms` then
# recomputes the star + planet_system positions using the new offset, which
# moves the planet_system back toward the origin (and the camera with it,
# since the camera is a child of planet_system). Result: camera ≈ (0,0,0)
# again, every absolute relative position preserved, no visible jump.
func _maybe_shift_origin() -> void:
	if floating_origin_threshold <= 0.0:
		return
	var cam := get_viewport().get_camera_3d()
	if cam == null:
		return
	var d2 := cam.global_position.length_squared()
	if d2 < floating_origin_threshold * floating_origin_threshold:
		return
	# Cast through GDScript `float` (64-bit) for accumulation precision.
	_origin_offset_x += float(cam.global_position.x)
	_origin_offset_y += float(cam.global_position.y)
	_origin_offset_z += float(cam.global_position.z)


# Toggle the WorldEnvironment fog to an underwater tint when the camera's
# distance from the planet center drops below sea level. Cheap to evaluate
# every frame; the actual `env.fog_enabled` toggle only flips when state
# changes.
func _update_underwater() -> void:
	if world_env == null:
		return
	var cam := get_viewport().get_camera_3d()
	if cam == null:
		return
	var sea_r := planet_radius + sea_level_offset
	var r := cam.global_position.distance_to(planet_system.global_position)
	var below := r < sea_r
	if below == _camera_underwater:
		return
	_camera_underwater = below
	var env := world_env.environment
	if env == null:
		return
	if below:
		env.fog_enabled = true
		env.fog_mode = Environment.FOG_MODE_EXPONENTIAL
		env.fog_light_color = Color(0.05, 0.18, 0.28)
		env.fog_light_energy = 0.85
		env.fog_density = 0.045
		env.fog_aerial_perspective = 0.0
		env.fog_sun_scatter = 0.0
		env.adjustment_saturation = 0.85
	else:
		env.fog_enabled = false
		env.adjustment_saturation = 1.1


# ────────────────────────────────────────────────────────────────────────────

func _build_environment() -> void:
	var env := Environment.new()
	env.background_mode = Environment.BG_SKY
	var sky := Sky.new()
	# Custom deep-space sky: dark gradient + procedural starfield + galaxy band
	# (shaders/stars.gdshader). Replaces the flat ProceduralSkyMaterial so orbit
	# and night-side views show stars instead of a featureless black void.
	var sky_mat := ShaderMaterial.new()
	sky_mat.shader = load("res://shaders/stars.gdshader")
	sky.sky_material = sky_mat
	env.sky = sky
	env.tonemap_mode = Environment.TONE_MAPPER_ACES
	# Lower exposure dims the entire HDR frame BEFORE tone-mapping, so the
	# atmosphere/clouds/terrain darken proportionally. The sun disc is at
	# emission ≈18 — still vastly above the glow HDR threshold (1.5) post-exposure,
	# so its bloom/corona is preserved while the rest of the scene calms down.
	env.tonemap_exposure = 0.7
	env.tonemap_white = 6.0
	env.ambient_light_source = Environment.AMBIENT_SOURCE_SKY
	env.ambient_light_sky_contribution = 0.35
	env.ambient_light_energy = 0.16   # lifted 0.10 → 0.16: a touch more sky fill so the terrain's shadowed micro-relief isn't crushed to dull flat grey
	env.glow_enabled = true
	# ADDITIVE blend (not the default SOFTLIGHT). Softlight barely registers
	# against a near-black space background — it's tuned for brightening dark
	# scenes subtly, which is exactly why the sun's corona was invisible. Additive
	# makes the bloom ADD light onto the black sky, so the corona actually shows.
	env.glow_blend_mode = Environment.GLOW_BLEND_MODE_ADDITIVE
	# The sun's corona comes from THRESHOLD glow (only pixels brighter than the
	# threshold bloom — i.e. just the sun disc), NOT from glow_bloom. Pushing the
	# threshold-glow strength + the wide octaves gives a big soft halo around the
	# sun while leaving the sub-threshold planet/clouds completely untouched.
	env.glow_intensity = 1.1
	env.glow_strength = 1.1
	# glow_bloom adds glow to the ENTIRE image regardless of brightness — that's
	# the scene-wide wash that blew out the planet, so it stays OFF. (The corona
	# is the threshold glow above, not this.)
	env.glow_bloom = 0.0
	# Threshold sits well below the sun disc (emission 26 — see sun material) but
	# above lit terrain / cloud tops, so ONLY the sun blooms.
	env.glow_hdr_threshold = 1.6
	env.glow_hdr_scale = 2.0
	# Concentrate the bloom in the MID octaves (3-4) for a tight corona rather than
	# a huge halo. The widest octaves (5-6) are what made the glow balloon across
	# the screen — 5 dialled right back, 6 off.
	env.set_glow_level(2, 0.7)
	env.set_glow_level(3, 1.0)
	env.set_glow_level(4, 0.7)
	env.set_glow_level(5, 0.35)
	env.set_glow_level(6, 0.0)
	env.adjustment_enabled = true
	env.adjustment_brightness = 0.98   # near-neutral: the old 0.85 leaned on glow_bloom's wash to brighten the scene; with the wash gone, knocking the frame down here was making the terrain read dim. 0.98 keeps a hair of deep-space contrast without crushing it
	env.adjustment_contrast = 1.08
	env.adjustment_saturation = 1.1
	# Screen-space ambient occlusion — contact shadows in terrain crevices and
	# around rocks / foliage bases / buildings, which grounds everything on foot
	# (no effect from orbit, where geometry is sub-pixel). Radius is metres, sized
	# for surface-scale relief; kept moderate so it reads as soft dirt-shadow, not a
	# hard outline. One screen pass — cheap on modern GPUs, and free far away.
	env.ssao_enabled = true
	env.ssao_radius = 2.5
	env.ssao_intensity = 2.0
	env.ssao_power = 1.5
	env.ssao_detail = 0.5
	world_env = WorldEnvironment.new()
	world_env.environment = env
	add_child(world_env)


func _build_star() -> void:
	star = Node3D.new()
	star.name = "Star"
	add_child(star)
	# Place the star at world origin. Planet orbits around (0,0,0).
	star.global_position = Vector3.ZERO

	sun_light = DirectionalLight3D.new()
	sun_light.name = "SunLight"
	sun_light.light_color = sun_color
	sun_light.light_energy = sun_energy
	sun_light.shadow_enabled = true
	sun_light.directional_shadow_mode = DirectionalLight3D.SHADOW_PARALLEL_4_SPLITS
	# Bigger max-distance so the shadow frustum covers more of the planet
	# without snapping pixel boundaries as the camera moves.
	sun_light.directional_shadow_max_distance = 2400.0
	sun_light.directional_shadow_split_1 = 0.06
	sun_light.directional_shadow_split_2 = 0.18
	sun_light.directional_shadow_split_3 = 0.45
	sun_light.directional_shadow_blend_splits = true
	# Planetary geometry needs a much bigger bias than the Godot default to
	# avoid shadow acne / self-shadow flicker on terrain that spans hundreds
	# of metres per chunk.
	sun_light.shadow_bias = 0.6
	sun_light.shadow_normal_bias = 3.0
	sun_light.shadow_opacity = 0.92
	star.add_child(sun_light)

	sun_visual = MeshInstance3D.new()
	sun_visual.name = "SunVisual"
	var sm := SphereMesh.new()
	sm.radius = sun_radius
	sm.height = sun_radius * 2.0
	# The sun is a featureless emissive ball ~1.8 M units away — it's a bloom
	# source, not detailed geometry. 64×32 (~4 k tris) was overkill; 24×12 reads
	# identically at this distance for a fraction of the verts. (A camera-facing
	# billboard quad would be true zero-geometry, but a sphere stays round from
	# every angle and avoids alpha/transparency-sorting fiddliness against the
	# atmosphere/cloud shells, so it's the simpler robust choice.)
	sm.radial_segments = 24
	sm.rings = 12
	sun_visual.mesh = sm
	sun_visual.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	sun_visual.gi_mode = GeometryInstance3D.GI_MODE_DISABLED
	sun_visual.extra_cull_margin = sun_radius
	var sun_m := StandardMaterial3D.new()
	# NOT unshaded: an unshaded StandardMaterial3D outputs ONLY albedo (clamped to
	# ~1.0) and ignores emission, so the sun never exceeded the HDR glow threshold
	# — its old "glow" was entirely glow_bloom's whole-screen wash, which is why
	# removing that wash killed it. Per-pixel shading lets emission (×26) through,
	# pushing the disc to ~26 in linear HDR. That's far above glow_hdr_threshold
	# (1.6) while lit terrain/clouds stay below it, so the threshold glow blooms
	# ONLY the sun into the corona — no scene-wide wash. disable_ambient_light +
	# no shadow keep the disc a clean flat bright colour despite being "shaded".
	sun_m.shading_mode = BaseMaterial3D.SHADING_MODE_PER_PIXEL
	sun_m.disable_ambient_light = true
	sun_m.albedo_color = sun_color
	sun_m.emission_enabled = true
	sun_m.emission = sun_color
	sun_m.emission_energy_multiplier = 26.0
	sun_visual.material_override = sun_m
	star.add_child(sun_visual)


func _build_planet_system() -> void:
	planet_system = Node3D.new()
	planet_system.name = "PlanetSystem"
	add_child(planet_system)

	# ── Planet ─────────────────────────────────────────────────────────────
	planet = Planet.new()
	planet.planet_radius = planet_radius
	planet.world_seed = world_seed
	planet.base_chunk_size = 48.0
	# +1 level vs. before: the planet is now ~2× the radius, so the coarsest
	# octree cells cover 2× the area each — without this the far/orbital view
	# would spawn ~4× as many top-level chunks. Finest detail is unchanged
	# (base_chunk_size is the same), this only adds a coarser root tier.
	# 11 (was 9): adds two genuinely-coarser orbital tiers. At radius 24 km the
	# root cell is now base_chunk_size·2^11 ≈ 98 km, with a ~9 km voxel — coarse,
	# but those tiers only become leaves hundreds of km out where the planet is a
	# few pixels, so the blockiness is sub-pixel while the chunk/tri count from
	# orbit drops sharply. Finest detail (LOD 0 = base_chunk_size) is untouched.
	# (Earlier I capped this at 9 citing an 8 km planet — that was the world.gd
	# default; main.gd runs at 24 km, so the body easily survives the coarser
	# voxels at these distances.)
	planet.max_lod = 11
	# Cells per axis per chunk. This — not lod_factor — is what controls triangle
	# density at the SPAWN altitude: the LOD of the chunk directly below the camera
	# is pinned by the discrete 2× LOD ladder (it's the same for any lod_factor in
	# ~[0.8, 1.6]), so lowering lod_factor only thins the mid/far field. Dropping
	# 12 → 8 coarsens the near field directly: the spawn-altitude chunk's voxels go
	# from ~128 m to ~192 m and the per-chunk triangle budget drops ~70%. Must stay
	# EVEN so the transition cells (which step the face in 2s) tile it fully.
	# Trade-off: LOD-0 voxels grow 4 m → 6 m, so close-up walking terrain is a touch
	# blockier — raise back toward 12 if that reads too coarse on foot.
	planet.voxel_resolution = 8
	# lod_factor = how aggressively chunks coarsen with camera distance: a chunk of
	# side `s` stays a leaf until the camera is within `s · lod_factor`. LOWER →
	# coarser sooner at every distance → fewer chunks and less surface detail when
	# pulled back (e.g. the 2.5 km spawn altitude), while the finest LOD when you
	# descend to walk is unchanged. Stepped down 2.2 → 2.0 → 1.6 to thin out the
	# spawn-altitude detail the user flagged (~1.6³/2.0³ ≈ half the chunks of 2.0).
	# Low values used to cause two-LOD-flip cracks, but those are now defended
	# structurally by the materialised-state balance net (_face_neighbor_has_finer_chunk)
	# + the atomic-swap free gate. Watch the lod_violations HUD: if it stays 0 you
	# can go lower still (1.4) for even less detail; if it climbs, this is the knob.
	planet.lod_factor = 1.6
	planet.collision_lod_max = 1
	# Was 16 — but planet.gd's own default/comment flags 16/tick as too slow:
	# with thousands of chunks pending it takes ~10 s to drain, far longer than
	# the atomic-swap hold window, so the frontier falls behind the camera and
	# cracks appear. The worker pool sits idle in the meantime (low CPU despite
	# low FPS). Now that take_all_ready marshals results in bulk, a wider gate is
	# affordable: keep the pool fed and the visible frontier ahead of the camera.
	planet.max_new_chunks_per_tick = 64
	planet.sea_level_offset = sea_level_offset
	planet.name = "Planet"
	terrain_mat = ShaderMaterial.new()
	terrain_mat.shader = load("res://shaders/terrain.gdshader")
	terrain_mat.set_shader_parameter("planet_center", Vector3.ZERO)
	terrain_mat.set_shader_parameter("planet_radius", planet_radius)
	terrain_mat.set_shader_parameter("polar_axis", Vector3.UP)
	# Altitudes in the terrain shader are measured from planet_radius (altitude =
	# r - planet_radius), but SEA sits at planet_radius + sea_level_offset (−200).
	# So all these thresholds are expressed relative to that −200 datum, otherwise
	# (e.g. beach_altitude = 8) the "beach" band starts ~208 m above the waterline
	# and paints sand across nearly all the low-lying land — which is exactly the
	# "everything is sand" bug. Sand now only hugs the actual shoreline.
	terrain_mat.set_shader_parameter("beach_altitude", sea_level_offset + 6.0)
	terrain_mat.set_shader_parameter("beach_fade", 18.0)
	# Snow line a few hundred metres above sea so mountains cap with snow. The
	# shader also drops temperature with altitude (lapse rate), so high peaks read
	# cold and get snow/ice even near the equator.
	terrain_mat.set_shader_parameter("snow_altitude", sea_level_offset + 650.0)
	terrain_mat.set_shader_parameter("snow_fade", 90.0)
	terrain_mat.set_shader_parameter("polar_cap_latitude", 0.82)
	terrain_mat.set_shader_parameter("polar_cap_fade", 0.10)
	# Lapse rate: high ground is colder. Reaches full strength ~1500 m above sea.
	terrain_mat.set_shader_parameter("lapse_rate", 0.6)
	terrain_mat.set_shader_parameter("lapse_full_altitude", 1500.0)
	# Procedurally-generated seamless PBR ground-detail texture (no files). Fed to the
	# terrain shader, which triplanar-samples it for albedo grain + roughness + the
	# micro-normal, so biomes read as real material surfaces close up.
	terrain_mat.set_shader_parameter("detail_grain_tex", _make_detail_grain_texture())
	planet.terrain_material = terrain_mat
	planet_system.add_child(planet)
	_apply_erosion_maps()
	_build_settlements()
	_build_rivers()
	_build_landmarks()

	# ── Atmosphere shell ───────────────────────────────────────────────────
	atmosphere = MeshInstance3D.new()
	atmosphere.name = "Atmosphere"
	# The TRIGGER mesh is much larger than the actual shell. The shader computes
	# scattering analytically against the real `atmosphere_radius` uniform and
	# discards rays that miss it, so the look is unchanged — but the mesh being
	# big means the camera is always deep inside it at normal altitudes and never
	# crosses the mesh surface right at the atmosphere boundary. Crossing the mesh
	# was the "instant/jarring" pop: its screen coverage jumped from the planet
	# disc (camera outside) to full-screen (camera inside) the moment you dipped
	# in. With the trigger well outside flight altitudes that transition is gone.
	var trigger_radius := atmosphere_radius * 2.5
	var amesh := SphereMesh.new()
	amesh.radius = trigger_radius
	amesh.height = trigger_radius * 2.0
	amesh.radial_segments = 64
	amesh.rings = 32
	atmosphere.mesh = amesh
	atmosphere.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	atmosphere.gi_mode = GeometryInstance3D.GI_MODE_DISABLED
	atmosphere.extra_cull_margin = trigger_radius
	atmosphere_mat = ShaderMaterial.new()
	atmosphere_mat.shader = load("res://shaders/atmosphere.gdshader")
	atmosphere_mat.set_shader_parameter("planet_center", Vector3.ZERO)
	atmosphere_mat.set_shader_parameter("planet_radius", planet_radius)
	atmosphere_mat.set_shader_parameter("atmosphere_radius", atmosphere_radius)
	atmosphere_mat.set_shader_parameter("rayleigh_color", Vector3(0.21, 0.45, 0.95))
	atmosphere_mat.set_shader_parameter("mie_color", Vector3(1.0, 0.85, 0.65))
	# Toned down (was 1.6 / 0.55): the atmosphere halo was overpowering the
	# surface and over-brightening the sky. Lower scattering keeps a believable
	# horizon haze without washing everything out.
	# Bumped (was 0.45 / 0.18): from the ground the atmosphere was almost
	# invisible — the user could see "through" the sky at distant terrain and
	# the boundary at the top of the shell looked like a hard edge against
	# space. 0.85 / 0.30 gives a proper visible blue sky from the ground while
	# the lowered sun_energy (0.55) keeps the surface itself from over-brightening.
	atmosphere_mat.set_shader_parameter("scattering_strength", 0.85)
	atmosphere_mat.set_shader_parameter("mie_strength", 0.30)
	# Concentric transparent shells (water < clouds < atmosphere) share the
	# planet centre, so Godot can't depth-sort them by camera distance and
	# their draw order flips frame-to-frame (the cloud/atmosphere flicker).
	# Pin an explicit order: outer shells draw last, over the inner ones.
	atmosphere_mat.render_priority = 2
	atmosphere.material_override = atmosphere_mat
	planet_system.add_child(atmosphere)

	# ── Water ocean ────────────────────────────────────────────────────────
	water = MeshInstance3D.new()
	water.name = "Water"
	var wmesh := SphereMesh.new()
	var wr := planet_radius + sea_level_offset
	wmesh.radius = wr
	wmesh.height = wr * 2.0
	# Dense tessellation: chord sag between sphere vertices is R·θ²/8 — at 96
	# segments on a ~24 km sphere that was ~13 m, so the polygonal sea surface
	# dipped metres below true sea level between vertices and opened visible
	# gaps against the terrain along shorelines. 384/192 brings the sag under
	# ~0.8 m; the vertex count (~74k) is trivial for one static mesh.
	wmesh.radial_segments = 384
	wmesh.rings = 192
	water.mesh = wmesh
	water.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	water.gi_mode = GeometryInstance3D.GI_MODE_DISABLED
	water.extra_cull_margin = wr
	water_mat = ShaderMaterial.new()
	water_mat.shader = load("res://shaders/water.gdshader")
	water_mat.set_shader_parameter("planet_center", Vector3.ZERO)
	water_mat.set_shader_parameter("planet_radius", planet_radius)
	water_mat.set_shader_parameter("sea_level_offset", sea_level_offset)
	water_mat.render_priority = 0
	water.material_override = water_mat
	planet_system.add_child(water)

	# ── Volumetric cloud deck ───────────────────────────────────────────────
	# Raymarched shell rendered on a sphere at the deck's outer radius. The
	# shader clips the view ray to [cloud_inner, cloud_outer] and marches it,
	# so it works from orbit, inside the deck, or on the ground looking up.
	clouds = MeshInstance3D.new()
	clouds.name = "Clouds"
	# TRIGGER mesh, larger than the actual deck. The shader clips the view ray to
	# [cloud_inner, cloud_outer] for the real cloud volume, so an oversized mesh
	# doesn't change the clouds — it just keeps the camera INSIDE the mesh while
	# it's near/just-above the deck top. Rendering on a sphere right at cloud_outer
	# meant that hovering around that altitude crossed the mesh surface, so looking
	# up clipped it away and the clouds blinked out. A 1.6× trigger pushes that
	# crossing far above normal flight.
	var cloud_trigger := cloud_outer_radius * 1.6
	var cmesh := SphereMesh.new()
	cmesh.radius = cloud_trigger
	cmesh.height = cloud_trigger * 2.0
	cmesh.radial_segments = 64
	cmesh.rings = 32
	clouds.mesh = cmesh
	clouds.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	clouds.gi_mode = GeometryInstance3D.GI_MODE_DISABLED
	clouds.extra_cull_margin = cloud_trigger
	cloud_mat = ShaderMaterial.new()
	cloud_mat.shader = load("res://shaders/clouds.gdshader")
	cloud_mat.set_shader_parameter("planet_center", Vector3.ZERO)
	cloud_mat.set_shader_parameter("planet_radius", planet_radius)
	cloud_mat.set_shader_parameter("cloud_inner", cloud_inner_radius)
	cloud_mat.set_shader_parameter("cloud_outer", cloud_outer_radius)
	cloud_mat.render_priority = 1
	clouds.material_override = cloud_mat
	planet_system.add_child(clouds)


# Placeholder cities + roads. The Rust density flattens a disc at each city site
# and a corridor along each road, so here we just drop visuals onto that flat
# ground: a MultiMesh of box "buildings" per pad and a dark ribbon per road.
# Parented under `planet` (the terrain's local, spinning frame) so they stay
# locked to the surface. Queried from a throwaway NativeTerrain so the sites
# match the exact pads the mesher carved (same seed + radius).
# Procedurally build a seamless tileable grain texture from layered noise — the PBR
# ground-detail map the terrain shader triplanar-samples (drives albedo grain,
# roughness variation and the micro-normal). No texture files: generated at load;
# NoiseTexture2D fills on a background thread, the shader uses white until ready.
func _make_detail_grain_texture() -> NoiseTexture2D:
	var tex := NoiseTexture2D.new()
	tex.width = 256
	tex.height = 256
	tex.seamless = true
	tex.generate_mipmaps = true
	var n := FastNoiseLite.new()
	n.noise_type = FastNoiseLite.TYPE_SIMPLEX_SMOOTH
	n.frequency = 0.035
	n.fractal_octaves = 4
	n.fractal_gain = 0.55
	n.seed = 1234
	tex.noise = n
	return tex


# Hand the baked erosion data (drainage flow + height delta) to the terrain
# shader as an equirect RG8 texture. The ground then READS the land's history —
# wet dark sediment along drainage channels, lusher deposition valleys — instead
# of colouring by local noise alone. ~9.4 MB of VRAM for the 3072×1536 grid.
# (Building the density here triggers the erosion bake/load synchronously; with
# the disk cache that's a file read on every run after the first.)
func _apply_erosion_maps() -> void:
	if not ClassDB.class_exists("NativeTerrain"):
		return
	var nt : Object = ClassDB.instantiate("NativeTerrain")
	var em : Dictionary = nt.call("erosion_texture", world_seed, planet_radius)
	var w : int = em.get("w", 0)
	var h : int = em.get("h", 0)
	var data : PackedByteArray = em.get("data", PackedByteArray())
	if w <= 0 or h <= 0 or data.size() != w * h * 2:
		return
	var img := Image.create_from_data(w, h, false, Image.FORMAT_RG8, data)
	var tex := ImageTexture.create_from_image(img)
	terrain_mat.set_shader_parameter("erosion_tex", tex)
	terrain_mat.set_shader_parameter("erosion_delta_range", float(em.get("range", 0.0)))


func _build_settlements() -> void:
	if not ClassDB.class_exists("NativeTerrain"):
		return
	var nt : Object = ClassDB.instantiate("NativeTerrain")
	var data : Dictionary = nt.call("settlement_data", world_seed, planet_radius)
	var centers : PackedVector3Array = data.get("centers", PackedVector3Array())
	if centers.is_empty():
		return
	settlement_centers = centers
	var road_points : PackedVector3Array = data.get("road_points", PackedVector3Array())
	var road_steps : int = data.get("road_steps", 0)
	var pad_radius : float = data.get("pad_radius", 200.0)   # the CITY pad size (fallback)
	# Per-settlement pad radius (cities are large, towns smaller). Parallel to centers.
	var pad_radii : PackedFloat32Array = data.get("pad_radii", PackedFloat32Array())
	# (Scatter keep-out around pads/roads is handled in Rust now — density.in_settlement.)

	var root := Node3D.new()
	root.name = "Settlements"

	# ── City ground: pavement disc + street grid + grid-aligned buildings ─────
	# Each pad is locally flat (pad_radius ≪ pad_r), so we work in a tangent frame
	# and project footprints back onto the sphere for curvature. A light concrete
	# disc is laid first, a darker street grid on top, then buildings fill the
	# blocks between the streets — so a town reads as a paved settlement rather
	# than boxes floating on grass. Pavement + streets are each one merged mesh
	# across all pads; buildings share one MultiMesh of unit boxes.
	var box := BoxMesh.new()
	box.size = Vector3.ONE
	var bmat := StandardMaterial3D.new()
	bmat.vertex_color_use_as_albedo = true
	bmat.roughness = 0.85
	bmat.metallic = 0.0

	var street_st := SurfaceTool.new()
	street_st.begin(Mesh.PRIMITIVE_TRIANGLES)
	var any_street := false

	var xforms : Array[Transform3D] = []
	var colors : Array[Color] = []
	var rng := RandomNumberGenerator.new()

	const CELL := 46.0          # block pitch — street centreline to street centreline
	const STREET_HALF := 5.0    # in-town road half-width
	const PAVE_FRAC := 0.92     # paved disc radius as a fraction of the pad radius

	for ci in centers.size():
		var center := centers[ci]
		var pad_r := center.length()
		if pad_r < 1.0:
			continue
		# This settlement's pad radius (cities large, towns ~half) and a 0..1 size
		# factor used to scale block density + building height so towns read smaller.
		var pad_radius_i : float = pad_radii[ci] if ci < pad_radii.size() else pad_radius
		var size_scale : float = clampf(pad_radius_i / 280.0, 0.25, 1.0)
		var up := center.normalized()
		var tangent := up.cross(Vector3.RIGHT)
		if tangent.length() < 0.01:
			tangent = up.cross(Vector3.FORWARD)
		tangent = tangent.normalized()
		var bitan := up.cross(tangent).normalized()
		var pave_r := pad_radius_i * PAVE_FRAC
		rng.seed = world_seed ^ (ci * 0x9E3779B1)
		# Per-city grid orientation: rotate the local frame by a random yaw so towns
		# don't all share the same axis-aligned street grid. Pavement/streets/buildings
		# and the height samples all use (tangent, bitan), so one rotation turns the
		# whole layout coherently.
		var grid_yaw := rng.randf_range(0.0, TAU)
		var _gt := tangent * cos(grid_yaw) + bitan * sin(grid_yaw)
		bitan = -tangent * sin(grid_yaw) + bitan * cos(grid_yaw)
		tangent = _gt

		# Incoming highway segments near this pad. Used below to keep buildings off
		# the avenue the highway takes into town (otherwise the inter-city road runs
		# straight through the building grid). road_points holds road_steps points
		# per road, concatenated.
		var hwy_a := PackedVector3Array()
		var hwy_b := PackedVector3Array()
		if road_steps >= 2 and road_points.size() >= road_steps:
			var nrds : int = int(road_points.size() / float(road_steps))
			for rr in nrds:
				var rb : int = rr * road_steps
				for si in road_steps - 1:
					var sa := road_points[rb + si]
					var sb := road_points[rb + si + 1]
					if center.distance_to((sa + sb) * 0.5) < pad_radius_i + 40.0:
						hwy_a.append(sa)
						hwy_b.append(sb)

		# ── Layout archetype ─────────────────────────────────────────────────
		# Same lot/street machinery, different ZONING GEOMETRY per settlement, so
		# towns stop sharing one circular core-ring-fringe stamp:
		#   0 GRID       — radial districts (the classic downtown-in-the-middle)
		#   1 LINEAR     — strip town stretched along the incoming highway
		#   2 WATERFRONT — downtown faces the downhill (sea) side, industry inland
		#   3 PLAZA      — open central square ringed by a dense civic core
		var arch_roll := rng.randf()
		var is_town := pad_radius_i < 200.0
		# Airport settlements: every third CITY gets an airfield strip on the pad
		# fringe — a runway corridor (buildings cleared below), hangars, a tower
		# and a parked flyable aircraft. air_oz is the runway centreline's lateral
		# offset in the (tangent, bitan) pad frame.
		var has_airport := (not is_town) and (ci % 3 == 0)
		var air_oz := pave_r * 0.55
		var arch : int
		if is_town:
			# Small settlements: mostly strips and plaza villages.
			arch = 1 if arch_roll < 0.45 else (3 if arch_roll < 0.70 else 0)
		else:
			arch = 0 if arch_roll < 0.28 else (2 if arch_roll < 0.55 else (1 if arch_roll < 0.78 else 3))
		# LINEAR aligns the whole frame (streets, blocks, buildings) to the highway
		# that enters town, so the strip follows the road instead of a random yaw.
		if arch == 1 and hwy_a.size() > 0:
			var seg := hwy_b[0] - hwy_a[0]
			seg = seg - up * seg.dot(up)
			if seg.length() > 1e-3:
				tangent = seg.normalized()
				bitan = up.cross(tangent).normalized()
		# Per-city fabric knobs: block pitch and skyline height vary city to city.
		var cell := CELL * rng.randf_range(0.85, 1.18)
		var h_mult := rng.randf_range(0.75, 1.35)

		# Sample the REAL carved ground across the pad in ONE native call, so the town
		# drapes onto the terrain (the pad is near-flat now) instead of a stamped flat
		# disc. A GRID×GRID height field over [-pad_radius, pad_radius] is then bilinear-
		# sampled by pad_point, so pavement / streets / buildings all follow the ground.
		# Finer grid (was 25) tracks the mesh more closely, so the foundation sits flush
		# instead of floating over the gaps the coarse grid smoothed across.
		var grid := 31
		var span := pad_radius_i
		var gdirs := PackedVector3Array()
		gdirs.resize(grid * grid)
		for gz in grid:
			for gx in grid:
				var ox0 := (float(gx) / float(grid - 1) * 2.0 - 1.0) * span
				var oz0 := (float(gz) / float(grid - 1) * 2.0 - 1.0) * span
				gdirs[gz * grid + gx] = (center + tangent * ox0 + bitan * oz0).normalized()
		var gheights : PackedFloat32Array = nt.call("surface_radii", world_seed, planet_radius, gdirs)

		# Local (tangent, bitan) offset → point on the CARVED ground, lifted by `h`.
		var pad_point := func(ox: float, oz: float, h: float) -> Vector3:
			var fx : float = clampf((ox / span * 0.5 + 0.5) * float(grid - 1), 0.0, float(grid - 1))
			var fz : float = clampf((oz / span * 0.5 + 0.5) * float(grid - 1), 0.0, float(grid - 1))
			var x0 := int(fx)
			var z0 := int(fz)
			var x1 : int = min(x0 + 1, grid - 1)
			var z1 : int = min(z0 + 1, grid - 1)
			var tx := fx - float(x0)
			var tz := fz - float(z0)
			var h0 : float = lerp(gheights[z0 * grid + x0], gheights[z0 * grid + x1], tx)
			var h1 : float = lerp(gheights[z1 * grid + x0], gheights[z1 * grid + x1], tx)
			var surf : float = lerp(h0, h1, tz)
			return (center + tangent * ox + bitan * oz).normalized() * (surf + h)

		# WATERFRONT: find the inland (uphill) direction from the height grid we just
		# sampled — least-squares slope of the carved ground across the footprint.
		# Downtown sits on the low (sea-facing) edge, industry drifts uphill/inland.
		var inland2 := Vector2.RIGHT
		if arch == 2:
			var gsum := Vector2.ZERO
			for gz in grid:
				for gx in grid:
					var ox0 := (float(gx) / float(grid - 1) * 2.0 - 1.0) * span
					var oz0 := (float(gz) / float(grid - 1) * 2.0 - 1.0) * span
					gsum += Vector2(ox0, oz0) * gheights[gz * grid + gx]
			if gsum.length() > 1e-3:
				inland2 = gsum.normalized()
		var plaza_open := maxf(cell * 1.1, pave_r * 0.18)   # PLAZA centre kept clear
		var strip_half := pave_r * 0.55                      # LINEAR lateral extent

		# District factor per block (0 = densest core, 1 = sparse fringe), shaped by
		# the archetype. The downstream core/residential/industrial buckets are
		# unchanged — only WHERE each district lands differs.
		var zone := func(bx: float, bz: float) -> float:
			match arch:
				1:  # strip: density falls off laterally, gently along the axis
					return clampf(absf(bz) / maxf(strip_half, 1.0) * 0.72
							+ absf(bx) / pave_r * 0.30, 0.0, 1.0)
				2:  # waterfront: gradient from the sea edge (core) to inland (fringe)
					var s := Vector2(bx, bz).dot(inland2) / pave_r
					return clampf(0.5 + s * 0.55 + Vector2(bx, bz).length() / pave_r * 0.15, 0.0, 1.0)
				3:  # plaza: densest ring right at the square, thinning outward
					return clampf(maxf(Vector2(bx, bz).length() - plaza_open, 0.0) / pave_r, 0.0, 1.0)
				_:  # radial classic
					return clampf(Vector2(bx, bz).length() / pave_r, 0.0, 1.0)

		# NO concrete disc — the city's ground is the URBAN TERRAIN the shader paints
		# (from the per-vertex settlement factor baked into the mesh) plus the dark
		# street grid and the buildings. The streets are laid straight on that ground.
		var n := int(pave_r / cell)
		for gi in range(-n, n + 1):
			var off := float(gi) * cell
			if absf(off) >= pave_r:
				continue
			var half_len : float = sqrt(maxf(pave_r * pave_r - off * off, 0.0))
			if arch == 1:
				# Strip town: along-axis streets only inside the strip; cross
				# streets clipped to the strip width.
				if absf(off) < strip_half:
					_emit_street_quad(street_st, pad_point, off, STREET_HALF, half_len, true, up)
				_emit_street_quad(street_st, pad_point, off, STREET_HALF, minf(half_len, strip_half), false, up)
			else:
				_emit_street_quad(street_st, pad_point, off, STREET_HALF, half_len, true, up)
				_emit_street_quad(street_st, pad_point, off, STREET_HALF, half_len, false, up)
			any_street = true

		# Buildings: each block is SUBDIVIDED into a small grid of lots, each with its
		# own building, so a block is shared by several buildings (a real city block)
		# rather than one box in an empty square. Lots fill most of their footprint,
		# separated by narrow alleys; heights vary for a real skyline.
		# Buildings, zoned into DISTRICTS by distance from the centre: a dense high-rise
		# CORE, a low-rise RESIDENTIAL ring, and a sparse INDUSTRIAL fringe of wide low
		# sheds — so a town reads as a real city with a skyline and a periphery, not a
		# uniform box grid. Each block is subdivided into lots; core lots grow tiered
		# towers (boxes stepped inward as they rise), the ring stays low-rise, the fringe
		# is warehouses.
		for bi in range(-n, n):
			for bj in range(-n, n):
				var bx := (float(bi) + 0.5) * cell
				var bz := (float(bj) + 0.5) * cell
				var bdist : float = Vector2(bx, bz).length()
				if bdist > pave_r - cell * 0.55:
					continue
				if arch == 1 and absf(bz) > strip_half:
					continue   # strip town: nothing beyond the strip's flanks
				if arch == 3 and bdist < plaza_open:
					continue   # plaza: the central square stays open
				if rng.randf() < 0.05:
					continue   # leave the odd block open for a plaza / park
				# District factor (0 = core, 1 = fringe), shaped by the archetype, with
				# a little noise so districts interlock instead of forming hard bands.
				var zt : float = clampf(zone.call(bx, bz) + rng.randf_range(-0.10, 0.10), 0.0, 1.0)
				var block := cell - STREET_HALF * 2.0
				var subx : int
				var subz : int
				var fill_lo : float
				var fill_hi : float
				var h_lo : float
				var h_hi : float
				var vacancy : float
				var tiered := false
				var industrial := false
				if zt < 0.32:
					# Core: dense small lots, tall tiered towers. `h_mult` varies the
					# skyline city-to-city; PLAZA cores read civic (taller ring).
					subx = rng.randi_range(2, 3); subz = rng.randi_range(2, 3)
					fill_lo = 0.80; fill_hi = 0.95
					h_lo = 34.0
					h_hi = lerp(60.0, 150.0, size_scale) * h_mult * (1.2 if arch == 3 else 1.0)
					vacancy = 0.05; tiered = true
				elif zt < 0.68:
					# Residential ring: low/mid-rise, denser.
					subx = rng.randi_range(2, 3); subz = rng.randi_range(2, 3)
					fill_lo = 0.66; fill_hi = 0.86
					h_lo = 8.0; h_hi = lerp(16.0, 34.0, size_scale) * h_mult
					vacancy = 0.12
				else:
					# Industrial / outskirts: big lots, wide low warehouses, sparse.
					subx = rng.randi_range(1, 2); subz = rng.randi_range(1, 2)
					fill_lo = 0.82; fill_hi = 0.97
					h_lo = 7.0; h_hi = 16.0
					vacancy = 0.30; industrial = true
				var lotx := block / float(subx)
				var lotz := block / float(subz)
				for sx in subx:
					for sz in subz:
						if rng.randf() < vacancy:
							continue   # courtyard / vacant lot
						var lox := bx + (float(sx) - (subx - 1) * 0.5) * lotx
						var loz := bz + (float(sz) - (subz - 1) * 0.5) * lotz
						var ground : Vector3 = pad_point.call(lox, loz, 0.0)
						# Skip lots the highway avenue runs through.
						if _near_segment(ground, hwy_a, hwy_b, 22.0):
							continue
						# Keep the airfield corridor (runway + apron) clear.
						if has_airport and absf(loz - air_oz) < 42.0:
							continue
						# Footprint fills most of the lot, leaving a narrow alley.
						var fx := lotx * rng.randf_range(fill_lo, fill_hi)
						var fz := lotz * rng.randf_range(fill_lo, fill_hi)
						var yaw := rng.randf_range(-0.04, 0.04)   # near grid-aligned
						var dir_x := tangent * cos(yaw) + bitan * sin(yaw)
						# dir_z = x_dir rotated −90° about up, so x × y stays right-handed.
						var dir_z := tangent * sin(yaw) - bitan * cos(yaw)
						# Embed the base into the slope so the downhill side doesn't float.
						var embed : float = maxf(fx, fz) * 0.12
						var bottom := ground - up * embed   # box base sits here
						var hy := rng.randf_range(h_lo, maxf(h_hi, h_lo + 2.0))
						xforms.append(Transform3D(
								Basis(dir_x * fx, up * hy, dir_z * fz), bottom + up * (hy * 0.5)))
						colors.append(_building_color(hy, zt, industrial, rng))
						# Tiered setbacks: core towers step inward as they rise.
						if tiered and hy > 60.0:
							var top := bottom + up * hy
							var tfx := fx
							var tfz := fz
							for _t in rng.randi_range(1, 2):
								tfx *= rng.randf_range(0.55, 0.74)
								tfz *= rng.randf_range(0.55, 0.74)
								var th := rng.randf_range(14.0, 34.0)
								xforms.append(Transform3D(
										Basis(dir_x * tfx, up * th, dir_z * tfz), top + up * (th * 0.5)))
								colors.append(_building_color(hy, zt, industrial, rng))
								top += up * th

		# Enterable outpost (interior system): one building per settlement with a
		# real walk-in interior, placed at the pavement edge facing the centre.
		_spawn_interior_outpost(root, pad_point, bitan, up, pave_r, span, ci)

		if has_airport:
			_build_airfield(root, pad_point, tangent, bitan, up, pave_r, air_oz, ci)

	# City streets — one merged dark mesh across all pads, laid on the urban ground.
	if any_street:
		var smat := StandardMaterial3D.new()
		smat.albedo_color = Color(0.13, 0.13, 0.14)
		smat.roughness = 0.95
		smat.metallic = 0.0
		smat.cull_mode = BaseMaterial3D.CULL_DISABLED
		var smi := MeshInstance3D.new()
		smi.name = "CityStreets"
		smi.mesh = street_st.commit()
		smi.material_override = smat
		root.add_child(smi)
		_attach_trimesh_collider(smi)

	if xforms.size() > 0:
		var mm := MultiMesh.new()
		mm.transform_format = MultiMesh.TRANSFORM_3D
		mm.use_colors = true
		mm.mesh = box
		mm.instance_count = xforms.size()
		for i in xforms.size():
			mm.set_instance_transform(i, xforms[i])
			mm.set_instance_color(i, colors[i])
		var mmi := MultiMeshInstance3D.new()
		mmi.name = "Buildings"
		mmi.multimesh = mm
		mmi.material_override = bmat
		root.add_child(mmi)
		# Collision: one combined trimesh of every building box so the walk-mode
		# player can't pass through them. Static + broadphase-culled, so a single
		# global body is fine (no per-instance bodies, no LOD needed).
		var bfaces := PackedVector3Array()
		var corners := [
			Vector3(-0.5, -0.5, -0.5), Vector3(0.5, -0.5, -0.5), Vector3(0.5, -0.5, 0.5), Vector3(-0.5, -0.5, 0.5),
			Vector3(-0.5, 0.5, -0.5), Vector3(0.5, 0.5, -0.5), Vector3(0.5, 0.5, 0.5), Vector3(-0.5, 0.5, 0.5),
		]
		var btris := [0, 1, 5, 0, 5, 4, 1, 2, 6, 1, 6, 5, 2, 3, 7, 2, 7, 6, 3, 0, 4, 3, 4, 7, 4, 5, 6, 4, 6, 7, 3, 2, 1, 3, 1, 0]
		for xf in xforms:
			for ti in btris:
				bfaces.append(xf * corners[ti])
		if bfaces.size() >= 3:
			var bshape := ConcavePolygonShape3D.new()
			bshape.set_faces(bfaces)
			var bbody := StaticBody3D.new()
			bbody.collision_layer = 1
			bbody.collision_mask = 0
			var bcs := CollisionShape3D.new()
			bcs.shape = bshape
			bbody.add_child(bcs)
			mmi.add_child(bbody)

	# ── Roads — a ribbon laid on each terrain-following centreline polyline ──
	# `road_points` is every road's centreline (already at the carved ground
	# height) concatenated, `road_steps` points per road. At each point the width
	# direction is the surface tangent perpendicular to the local travel direction,
	# so the ribbon banks with the ground instead of using one fixed arc-plane
	# normal — it conforms to hills and bends.
	if road_points.size() >= 2 and road_steps >= 2:
		var st := SurfaceTool.new()
		st.begin(Mesh.PRIMITIVE_TRIANGLES)
		var road_half := 16.0
		var any_road := false
		# road_points holds road_steps points per road, concatenated — an exact
		# multiple; float-divide then truncate for the count without the warning.
		var num_roads : int = int(road_points.size() / float(road_steps))
		# Run the ribbon in to a small central plaza (not the pavement edge) so the
		# highways from several towns CONVERGE at the centre — a crossroads — instead
		# of each ending as a separate stub at the rim. Across the pad the carved
		# ground is the flat pad height and the ribbon (lifted) rides above the
		# pavement/street grid as the main avenue (buildings are already cleared from
		# its path). Stopping a little short of the exact centre leaves a plaza and
		# avoids the converging ribbons overlapping into a z-fighting blob.
		var plaza_r := 32.0
		for r in num_roads:
			var base : int = r * road_steps
			var prev_l := Vector3.ZERO
			var prev_r := Vector3.ZERO
			var has_prev := false
			for i in road_steps:
				var cp := road_points[base + i]
				var up := cp.normalized()
				var in_plaza := false
				for c in centers:
					if cp.distance_to(c) < plaza_r:
						in_plaza = true
						break
				if in_plaza:
					has_prev = false
					continue
				# Local travel direction from the neighbouring points.
				var ahead : Vector3 = road_points[base + min(i + 1, road_steps - 1)]
				var behind : Vector3 = road_points[base + max(i - 1, 0)]
				var travel := (ahead - behind)
				travel = (travel - up * travel.dot(up))   # project onto the surface
				if travel.length() < 1e-4:
					has_prev = false
					continue
				travel = travel.normalized()
				var nrm := up.cross(travel).normalized()   # width direction, on the surface
				# Sit just above the carved road bed (cp is the bed, ~6 m below grade).
				# 5.0 put the ribbon near the TOP of the cut so it floated ~5 m over the
				# bed; 2.0 lays it on the bed so the road reads as sitting in its cut.
				var center := cp + up * 2.0
				var lft := center + nrm * road_half
				var rgt := center - nrm * road_half
				if has_prev:
					st.set_normal(up); st.add_vertex(prev_l)
					st.set_normal(up); st.add_vertex(prev_r)
					st.set_normal(up); st.add_vertex(lft)
					st.set_normal(up); st.add_vertex(prev_r)
					st.set_normal(up); st.add_vertex(rgt)
					st.set_normal(up); st.add_vertex(lft)
					any_road = true
				prev_l = lft
				prev_r = rgt
				has_prev = true
		if any_road:
			var rmesh := st.commit()
			var rmi := MeshInstance3D.new()
			rmi.name = "Roads"
			rmi.mesh = rmesh
			var rmat := StandardMaterial3D.new()
			rmat.albedo_color = Color(0.12, 0.12, 0.13)
			rmat.roughness = 0.95
			rmat.metallic = 0.0
			rmat.cull_mode = BaseMaterial3D.CULL_DISABLED
			rmi.material_override = rmat
			root.add_child(rmi)
			_attach_trimesh_collider(rmi)

	# Power lines: poles + slung wires beside every highway, linking the towns —
	# the "electricity connecting the areas" of the Rust-on-a-planet feel.
	_build_power_lines(root, road_points, road_steps)

	planet.add_child(root)


# ── Airfields (airport settlements) ───────────────────────────────────────────
# A runway strip laid on the carved pad ground (same height-following quads as
# the streets), centreline markings, two hangars, a control tower, and a parked
# flyable Aircraft (the godotflight fixed-wing port) at the runway threshold.
func _build_airfield(parent: Node3D, pad_point: Callable, tangent: Vector3,
		bitan: Vector3, up: Vector3, pave_r: float, air_oz: float, ci: int) -> void:
	var half_len : float = sqrt(maxf(pave_r * pave_r - air_oz * air_oz, 0.0)) * 0.95
	if half_len < 90.0:
		return
	const RUNWAY_HALF := 10.0
	var field := Node3D.new()
	field.name = "Airfield%d" % ci

	# Runway surface — segmented quads following the ground, slightly above the
	# street layer so it reads on top.
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	var segs := 24
	var prev_l : Vector3
	var prev_r : Vector3
	for i in segs + 1:
		var ox : float = lerpf(-half_len, half_len, float(i) / float(segs))
		var lft : Vector3 = pad_point.call(ox, air_oz - RUNWAY_HALF, 0.45)
		var rgt : Vector3 = pad_point.call(ox, air_oz + RUNWAY_HALF, 0.45)
		if i > 0:
			st.set_normal(up); st.add_vertex(prev_l)
			st.set_normal(up); st.add_vertex(prev_r)
			st.set_normal(up); st.add_vertex(lft)
			st.set_normal(up); st.add_vertex(prev_r)
			st.set_normal(up); st.add_vertex(rgt)
			st.set_normal(up); st.add_vertex(lft)
		prev_l = lft
		prev_r = rgt
	var rmat := StandardMaterial3D.new()
	rmat.albedo_color = Color(0.10, 0.10, 0.11)
	rmat.roughness = 0.95
	rmat.cull_mode = BaseMaterial3D.CULL_DISABLED
	var rmi := MeshInstance3D.new()
	rmi.name = "Runway"
	rmi.mesh = st.commit()
	rmi.material_override = rmat
	field.add_child(rmi)

	# Centreline dashes — thin white quads just above the asphalt.
	var dash_st := SurfaceTool.new()
	dash_st.begin(Mesh.PRIMITIVE_TRIANGLES)
	var dash_len := 6.0
	var dash_gap := 10.0
	var ox_d := -half_len + 20.0
	while ox_d < half_len - 20.0:
		var a : Vector3 = pad_point.call(ox_d, air_oz - 0.35, 0.55)
		var b : Vector3 = pad_point.call(ox_d, air_oz + 0.35, 0.55)
		var c : Vector3 = pad_point.call(ox_d + dash_len, air_oz + 0.35, 0.55)
		var d : Vector3 = pad_point.call(ox_d + dash_len, air_oz - 0.35, 0.55)
		dash_st.set_normal(up); dash_st.add_vertex(a)
		dash_st.set_normal(up); dash_st.add_vertex(b)
		dash_st.set_normal(up); dash_st.add_vertex(c)
		dash_st.set_normal(up); dash_st.add_vertex(a)
		dash_st.set_normal(up); dash_st.add_vertex(c)
		dash_st.set_normal(up); dash_st.add_vertex(d)
		ox_d += dash_len + dash_gap
	var dmat := StandardMaterial3D.new()
	dmat.albedo_color = Color(0.92, 0.92, 0.90)
	dmat.roughness = 0.8
	dmat.cull_mode = BaseMaterial3D.CULL_DISABLED
	var dmi := MeshInstance3D.new()
	dmi.name = "RunwayMarkings"
	dmi.mesh = dash_st.commit()
	dmi.material_override = dmat
	field.add_child(dmi)

	# Buildings stand on the apron side (away from town centre = +bitan).
	# Right-handed surface frame: x = tangent, y = up, z = -bitan.
	var frame := Basis(tangent, up, -bitan)
	var hangar_mat := StandardMaterial3D.new()
	hangar_mat.albedo_color = Color(0.45, 0.47, 0.50)
	hangar_mat.roughness = 0.6
	hangar_mat.metallic = 0.4
	for k in 2:
		var hx := -50.0 + float(k) * 100.0
		var hpos : Vector3 = pad_point.call(hx, air_oz + 30.0, 0.0)
		_airfield_box(field, frame, hpos, up, Vector3(26.0, 9.0, 18.0), hangar_mat)
	# Control tower: shaft + cab.
	var tower_mat := StandardMaterial3D.new()
	tower_mat.albedo_color = Color(0.75, 0.75, 0.78)
	tower_mat.roughness = 0.5
	var tpos : Vector3 = pad_point.call(half_len * 0.7, air_oz + 28.0, 0.0)
	_airfield_box(field, frame, tpos, up, Vector3(5.0, 18.0, 5.0), tower_mat)
	var cab_mat := StandardMaterial3D.new()
	cab_mat.albedo_color = Color(0.15, 0.25, 0.32)
	cab_mat.roughness = 0.2
	cab_mat.metallic = 0.6
	_airfield_box(field, frame, tpos + up * 18.0, up, Vector3(8.0, 3.5, 8.0), cab_mat)

	parent.add_child(field)
	_attach_trimesh_collider(rmi)

	# Parked aircraft at the runway threshold, nose down the strip (+tangent).
	var craft := Aircraft.new()
	craft.name = "Aircraft%d" % ci
	craft.planet = planet
	var cb := Basis(-bitan, up, -tangent)
	craft.transform = Transform3D(cb, pad_point.call(-half_len * 0.6, air_oz, 1.6))
	craft.freeze = true   # parked: ride the planet spin kinematically
	parent.add_child(craft)


# A box with its base at `base_pos`, oriented by the orthonormal surface frame,
# plus a matching StaticBody3D collider on the environment layer.
func _airfield_box(parent: Node3D, frame: Basis, base_pos: Vector3, up: Vector3,
		size: Vector3, mat: Material) -> void:
	var mi := MeshInstance3D.new()
	var bm := BoxMesh.new()
	bm.size = size
	mi.mesh = bm
	mi.material_override = mat
	mi.transform = Transform3D(frame, base_pos + up * (size.y * 0.5 - 0.4))
	parent.add_child(mi)
	var body := StaticBody3D.new()
	body.collision_layer = 1
	body.collision_mask = 0
	var cs := CollisionShape3D.new()
	var bs := BoxShape3D.new()
	bs.size = size
	cs.shape = bs
	body.add_child(cs)
	mi.add_child(body)


# ── Enterable outposts (interior system) ──────────────────────────────────────
# Builds a small structure with a real interior from the ported InteriorLayout /
# InteriorGenerator classes: visual wall/floor boxes plus a layer-1 StaticBody3D
# so the WALK-mode player can step inside through the open front wall. Layout
# variant cycles per settlement (single room / two rooms / corridor / L-shape).
func _spawn_interior_outpost(parent: Node3D, pad_point: Callable, bitan: Vector3,
		up: Vector3, pave_r: float, span: float, ci: int) -> void:
	# Sit just outside the paved disc but inside the sampled height grid.
	var d := minf(pave_r * 1.04, span * 0.96)
	var ground : Vector3 = pad_point.call(0.0, d, 0.0)
	var layout : InteriorLayout = InteriorLayout.create_from_type(ci % 4, 1.0)

	var outpost := Node3D.new()
	outpost.name = "Outpost%d" % ci
	# Layout frame: Y up, entrance toward local +Z. Face the entrance back
	# toward the town centre (-bitan) so it opens onto the pavement.
	var z_dir := -bitan
	var x_dir := up.cross(z_dir).normalized()
	z_dir = x_dir.cross(up).normalized()
	# Room boxes are centred on the node origin vertically (height 3 m), so
	# lift by half the height minus a small embed against slope gaps.
	outpost.transform = Transform3D(Basis(x_dir, up, z_dir), ground + up * (1.5 - 0.25))
	InteriorGenerator.generate_visuals(layout, outpost)
	outpost.add_child(InteriorGenerator.generate_static_body(layout))
	parent.add_child(outpost)


# Rivers/streams — water ribbons laid in the channels the global erosion field
# carved (see rust/src/erosion.rs). The native side traces each course downhill
# from a highland source to the sea and returns floor points already at the exact
# terrain surface, plus a per-point width factor (flow) so rivers widen downstream.
# We lay a translucent ribbon along each, banking with the ground like the roads.
func _build_rivers() -> void:
	if not ClassDB.class_exists("NativeTerrain"):
		return
	var nt : Object = ClassDB.instantiate("NativeTerrain")
	var data : Dictionary = nt.call("river_data", world_seed, planet_radius, sea_level_offset)
	var points : PackedVector3Array = data.get("points", PackedVector3Array())
	var lengths : PackedInt32Array = data.get("lengths", PackedInt32Array())
	var widths : PackedFloat32Array = data.get("widths", PackedFloat32Array())
	if points.size() < 2 or lengths.is_empty():
		return

	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	var any := false
	var base := 0
	for li in lengths.size():
		var count : int = lengths[li]
		if count >= 2:
			var prev_l := Vector3.ZERO
			var prev_r := Vector3.ZERO
			var prev_col := Color.WHITE
			var has_prev := false
			for i in count:
				var cp := points[base + i]
				var up := cp.normalized()
				# Travel direction along the course, projected onto the surface.
				var ahead : Vector3 = points[base + min(i + 1, count - 1)]
				var behind : Vector3 = points[base + max(i - 1, 0)]
				var travel := ahead - behind
				travel = travel - up * travel.dot(up)
				if travel.length() < 1e-4:
					has_prev = false
					continue
				# Rapids / waterfalls: where the course drops steeply between
				# neighbouring points, the water whitens into foam (vertex colour;
				# the material multiplies it over the water tint). Steepness =
				# radial drop over surface run between the draped points.
				var drop : float = behind.length() - ahead.length()
				var run : float = maxf(travel.length(), 0.5)
				var steep : float = clampf(drop / run, 0.0, 1.0)
				var foam : float = smoothstep(0.25, 0.7, steep)
				var col := Color(0.17, 0.40, 0.60, 0.74).lerp(Color(0.88, 0.93, 0.96, 0.92), foam)
				travel = travel.normalized()
				var nrm := up.cross(travel).normalized()
				# Widen downstream with flow; sit just above the channel floor
				# (a touch higher where it foams, so rapids read over the rock).
				var half : float = lerp(4.0, 24.0, widths[base + i])
				var center := cp + up * (2.0 + foam * 1.2)
				var lft := center + nrm * half
				var rgt := center - nrm * half
				if has_prev:
					st.set_color(prev_col); st.set_normal(up); st.add_vertex(prev_l)
					st.set_color(prev_col); st.set_normal(up); st.add_vertex(prev_r)
					st.set_color(col); st.set_normal(up); st.add_vertex(lft)
					st.set_color(prev_col); st.set_normal(up); st.add_vertex(prev_r)
					st.set_color(col); st.set_normal(up); st.add_vertex(rgt)
					st.set_color(col); st.set_normal(up); st.add_vertex(lft)
					any = true
				prev_l = lft
				prev_r = rgt
				prev_col = col
				has_prev = true
		base += count

	# Lakes — flat water discs where rivers pooled in inland basins. Added to the
	# same water mesh/material as the rivers. Each centre is already at the lake's
	# water surface; the rim is projected back onto the sphere for curvature.
	var lakes : PackedVector3Array = data.get("lakes", PackedVector3Array())
	var lake_radii : PackedFloat32Array = data.get("lake_radii", PackedFloat32Array())
	for li in lakes.size():
		var c := lakes[li]
		var rad : float = lake_radii[li]
		var surf_r := c.length()
		if surf_r < 1.0:
			continue
		var up := c.normalized()
		var t := up.cross(Vector3.RIGHT)
		if t.length() < 0.01:
			t = up.cross(Vector3.FORWARD)
		t = t.normalized()
		var bt := up.cross(t).normalized()
		var segs := 28
		var hub := c + up * 0.4
		var lake_col := Color(0.15, 0.38, 0.58, 0.78)
		for s in segs:
			var a0 := TAU * float(s) / float(segs)
			var a1 := TAU * float(s + 1) / float(segs)
			var p0 := (c + (t * cos(a0) + bt * sin(a0)) * rad).normalized() * surf_r + up * 0.4
			var p1 := (c + (t * cos(a1) + bt * sin(a1)) * rad).normalized() * surf_r + up * 0.4
			st.set_color(lake_col); st.set_normal(up); st.add_vertex(hub)
			st.set_color(lake_col); st.set_normal(up); st.add_vertex(p1)
			st.set_color(lake_col); st.set_normal(up); st.add_vertex(p0)
		any = true

	if not any:
		return
	var rmesh := st.commit()
	var rmi := MeshInstance3D.new()
	rmi.name = "RiversAndLakes"
	rmi.mesh = rmesh
	var rmat := StandardMaterial3D.new()
	# Colour (incl. the foam whitening on rapids/waterfalls) is per-vertex now.
	rmat.albedo_color = Color.WHITE
	rmat.vertex_color_use_as_albedo = true
	rmat.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	rmat.roughness = 0.12
	rmat.metallic = 0.0
	rmat.cull_mode = BaseMaterial3D.CULL_DISABLED
	rmi.material_override = rmat
	planet.add_child(rmi)


# Region landmarks — a distinct placeholder monument at each continent-cluster
# centre, so different regions read apart from orbit and on foot. The native side
# returns one anchor per region (on the terrain surface, local frame); the kind of
# monument cycles by region index: obelisk, monolith ring, stepped pyramid.
func _build_landmarks() -> void:
	if not ClassDB.class_exists("NativeTerrain"):
		return
	var nt : Object = ClassDB.instantiate("NativeTerrain")
	var anchors : PackedVector3Array = nt.call("region_data", world_seed, planet_radius)
	if anchors.is_empty():
		return
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	for ri in anchors.size():
		var base := anchors[ri]
		if base.length() < 1.0:
			continue
		var up := base.normalized()
		var tangent := up.cross(Vector3.RIGHT)
		if tangent.length() < 0.01:
			tangent = up.cross(Vector3.FORWARD)
		tangent = tangent.normalized()
		var bitan := up.cross(tangent).normalized()
		var col := Color(0.50, 0.48, 0.45).lerp(Color(0.40, 0.36, 0.34), float(ri % 3) / 2.0)
		match ri % 3:
			0:
				# Obelisk: a tall tapered spire (wide base box + a thin tall box).
				_add_landmark_box(st, base, up, tangent, bitan, 14.0, 8.0, 14.0, col)
				_add_landmark_box(st, base + up * 16.0, up, tangent, bitan, 7.0, 60.0, 7.0, col)
			1:
				# Monolith ring: several tall standing stones in a circle.
				var stones := 7
				for s in stones:
					var a := TAU * float(s) / float(stones)
					var off := (tangent * cos(a) + bitan * sin(a)) * 44.0
					_add_landmark_box(st, base + off, up, tangent, bitan, 5.0, 26.0, 9.0, col)
			_:
				# Stepped pyramid: stacked shrinking boxes.
				var tiers := 4
				for ti in tiers:
					var half : float = lerp(34.0, 8.0, float(ti) / float(tiers - 1))
					var y := float(ti) * 16.0
					_add_landmark_box(st, base + up * y, up, tangent, bitan, half, 8.0, half, col)
	var mesh := st.commit()
	if mesh == null:
		return
	var mat := StandardMaterial3D.new()
	mat.vertex_color_use_as_albedo = true
	mat.roughness = 0.9
	mat.metallic = 0.0
	var mi := MeshInstance3D.new()
	mi.name = "RegionLandmarks"
	mi.mesh = mesh
	mi.material_override = mat
	planet.add_child(mi)
	_attach_trimesh_collider(mi)


# Add one axis-aligned-in-the-tangent-frame box to a landmark mesh. `center` is the
# box's BASE point (on the ground); the box rises `2*hy` along `up`, spanning ±hx
# along `tangent` and ±hz along `bitan`. Vertex-coloured `col`.
func _add_landmark_box(st: SurfaceTool, center: Vector3, up: Vector3,
		tangent: Vector3, bitan: Vector3, hx: float, hy: float, hz: float, col: Color) -> void:
	var c := center + up * hy   # box centre (base sits on the ground)
	var x := tangent * hx
	var y := up * hy
	var z := bitan * hz
	var p := [
		c - x - y - z, c + x - y - z, c + x - y + z, c - x - y + z,
		c - x + y - z, c + x + y - z, c + x + y + z, c - x + y + z,
	]
	var faces := [
		[0, 1, 5], [0, 5, 4], [1, 2, 6], [1, 6, 5], [2, 3, 7], [2, 7, 6],
		[3, 0, 4], [3, 4, 7], [4, 5, 6], [4, 6, 7], [3, 2, 1], [3, 1, 0],
	]
	for f in faces:
		var a : Vector3 = p[f[0]]
		var b : Vector3 = p[f[1]]
		var d : Vector3 = p[f[2]]
		var nn := (b - a).cross(d - a).normalized()
		st.set_color(col); st.set_normal(nn); st.add_vertex(a)
		st.set_color(col); st.set_normal(nn); st.add_vertex(b)
		st.set_color(col); st.set_normal(nn); st.add_vertex(d)


# Emit one street ribbon quad onto a city pad, clipped to the paved disc. `off` is
# the line's offset along one axis; the ribbon spans ±half_len along the other,
# is 2·half_w wide, and is lifted just above the pavement. `along_bitan` picks
# which axis the street runs along. `pad_point` maps (tangent, bitan, lift) → a
# point on the flat pad sphere (the closure built per pad in _build_settlements).
func _emit_street_quad(st: SurfaceTool, pad_point: Callable, off: float,
		half_w: float, half_len: float, along_bitan: bool, up: Vector3) -> void:
	# Just above the pavement so the grid reads as a road surface without floating.
	var lift := 0.9
	# SUBDIVIDED along the length: a single quad across the pad is a straight
	# CHORD, and over a ~500 m pad on a 24 km sphere the chord sags ~1.4 m below
	# the (now exactly spherical) flat pad — streets were buried mid-span and
	# floated at the ends. Short segments draped per-vertex follow the curvature.
	const SEG_LEN := 32.0
	var segs : int = maxi(int(ceil(half_len * 2.0 / SEG_LEN)), 1)
	var prev_a : Vector3
	var prev_b : Vector3
	for si in segs + 1:
		var l := -half_len + half_len * 2.0 * float(si) / float(segs)
		var a : Vector3
		var b : Vector3
		if along_bitan:
			# Runs along bitan (oz); width in tangent (ox) around `off`.
			a = pad_point.call(off - half_w, l, lift)
			b = pad_point.call(off + half_w, l, lift)
		else:
			# Runs along tangent (ox); width in bitan (oz) around `off`.
			a = pad_point.call(l, off - half_w, lift)
			b = pad_point.call(l, off + half_w, lift)
		if si > 0:
			st.set_normal(up); st.add_vertex(prev_a)
			st.set_normal(up); st.add_vertex(prev_b)
			st.set_normal(up); st.add_vertex(b)
			st.set_normal(up); st.add_vertex(prev_a)
			st.set_normal(up); st.add_vertex(b)
			st.set_normal(up); st.add_vertex(a)
		prev_a = a
		prev_b = b


# Power lines along the highways: a pole every few road samples (offset to the
# verge), a cross-arm at the top, and wires slung pole-to-pole with a little sag.
# Connects the settlements visually — the electricity grid of a Rust-style world.
func _build_power_lines(parent: Node3D, road_points: PackedVector3Array, road_steps: int) -> void:
	if road_points.size() < 2 or road_steps < 2:
		return
	var pole_st := SurfaceTool.new()
	pole_st.begin(Mesh.PRIMITIVE_TRIANGLES)
	var wire_st := SurfaceTool.new()
	wire_st.begin(Mesh.PRIMITIVE_TRIANGLES)
	var pole_col := Color(0.20, 0.16, 0.12)
	var wire_col := Color(0.04, 0.04, 0.05)
	var num_roads : int = int(road_points.size() / float(road_steps))
	const POLE_SPACING := 8        # road samples between poles
	const POLE_HEIGHT := 16.0
	const POLE_SIDE := 24.0        # offset from the road centreline to the verge
	var any := false
	for r in num_roads:
		var base : int = r * road_steps
		var prev_top := Vector3.ZERO
		var has_prev := false
		var i := 0
		while i < road_steps:
			var cp := road_points[base + i]
			var up := cp.normalized()
			var ahead : Vector3 = road_points[base + min(i + 1, road_steps - 1)]
			var behind : Vector3 = road_points[base + max(i - 1, 0)]
			var travel := ahead - behind
			travel = travel - up * travel.dot(up)
			if travel.length() < 1e-4:
				i += POLE_SPACING
				continue
			travel = travel.normalized()
			var side := up.cross(travel).normalized()
			var base_pt := cp + side * POLE_SIDE + up * 1.0
			var top := base_pt + up * POLE_HEIGHT
			_add_segment_box(pole_st, base_pt, top, 0.6, side, pole_col)             # pole
			_add_segment_box(pole_st, top - side * 3.0, top + side * 3.0, 0.4, up, pole_col)  # cross-arm
			if has_prev:
				var mid := (prev_top + top) * 0.5 - up * 2.5   # catenary sag
				_add_segment_box(wire_st, prev_top, mid, 0.16, up, wire_col)
				_add_segment_box(wire_st, mid, top, 0.16, up, wire_col)
				any = true
			prev_top = top
			has_prev = true
			i += POLE_SPACING
	var pmesh := pole_st.commit()
	if pmesh != null and pmesh.get_surface_count() > 0:
		var pmat := StandardMaterial3D.new()
		pmat.vertex_color_use_as_albedo = true
		pmat.roughness = 0.9
		var pmi := MeshInstance3D.new()
		pmi.name = "PowerPoles"
		pmi.mesh = pmesh
		pmi.material_override = pmat
		parent.add_child(pmi)
	if any:
		var wmesh := wire_st.commit()
		var wmat := StandardMaterial3D.new()
		wmat.vertex_color_use_as_albedo = true
		wmat.roughness = 0.5
		var wmi := MeshInstance3D.new()
		wmi.name = "PowerWires"
		wmi.mesh = wmesh
		wmi.material_override = wmat
		parent.add_child(wmi)


# Build a thin box (square cross-section, half-extent `half`) from `a` to `b` into a
# SurfaceTool — used for power poles, cross-arms and wires. `up_hint` disambiguates
# the cross-section orientation for near-vertical / near-horizontal segments.
func _add_segment_box(st: SurfaceTool, a: Vector3, b: Vector3, half: float, up_hint: Vector3, col: Color) -> void:
	var axis := b - a
	var ln := axis.length()
	if ln < 1e-4:
		return
	var dir := axis / ln
	var u := dir.cross(up_hint)
	if u.length() < 1e-4:
		u = dir.cross(Vector3.RIGHT)
	u = u.normalized() * half
	var v := dir.cross(u).normalized() * half
	var p := [a - u - v, a + u - v, a + u + v, a - u + v, b - u - v, b + u - v, b + u + v, b - u + v]
	var faces := [
		[0, 1, 5], [0, 5, 4], [1, 2, 6], [1, 6, 5], [2, 3, 7], [2, 7, 6],
		[3, 0, 4], [3, 4, 7], [0, 3, 2], [0, 2, 1], [4, 5, 6], [4, 6, 7],
	]
	for f in faces:
		var p0 : Vector3 = p[f[0]]
		var p1 : Vector3 = p[f[1]]
		var p2 : Vector3 = p[f[2]]
		var nn := (p1 - p0).cross(p2 - p0).normalized()
		st.set_color(col); st.set_normal(nn); st.add_vertex(p0)
		st.set_color(col); st.set_normal(nn); st.add_vertex(p1)
		st.set_color(col); st.set_normal(nn); st.add_vertex(p2)


# Attach a static trimesh collider (physics layer 1) to a built man-made mesh so
# the walk-mode player can stand on / bump into it. These meshes are static and
# low-poly (one per planet), so a single global body each is fine — Godot's
# broadphase culls them by distance, so there's no need to LOD or chunk them.
func _attach_trimesh_collider(mi: MeshInstance3D) -> void:
	if mi.mesh == null:
		return
	var shape := mi.mesh.create_trimesh_shape()
	if shape == null:
		return
	var body := StaticBody3D.new()
	body.collision_layer = 1
	body.collision_mask = 0
	var cs := CollisionShape3D.new()
	cs.shape = shape
	body.add_child(cs)
	mi.add_child(body)


# True if `p` is within `half` of any segment in the parallel (a[i], b[i]) lists.
# Used to keep city buildings off the avenue an incoming highway takes into town.
func _near_segment(p: Vector3, sa: PackedVector3Array, sb: PackedVector3Array, half: float) -> bool:
	var half2 := half * half
	for i in sa.size():
		var a := sa[i]
		var ab := sb[i] - a
		var denom := ab.length_squared()
		var t := 0.0 if denom < 1e-6 else clampf((p - a).dot(ab) / denom, 0.0, 1.0)
		if p.distance_squared_to(a + ab * t) <= half2:
			return true
	return false


# Per-building colour by district + height: cool glass/steel for tall core towers,
# warm brick/stucco for residential low-rise, muted tan/grey (the odd rusty shed) for
# industrial — with per-building variation so a block never looks tiled.
func _building_color(hy: float, zt: float, industrial: bool, rng: RandomNumberGenerator) -> Color:
	if industrial:
		var m := rng.randf_range(0.42, 0.60)
		if rng.randf() < 0.18:
			return Color(m * 1.15, m * 0.78, m * 0.62)   # rusty / weathered shed
		return Color(m * 1.04, m * 1.02, m * 0.96)        # pale corrugated grey
	var tower_t : float = clampf((hy - 45.0) / 70.0, 0.0, 1.0)
	if zt < 0.34 and rng.randf() < (0.35 + tower_t * 0.5):
		# Glass/steel tower — cool, slightly blue, brighter the taller it is.
		var b : float = rng.randf_range(0.52, 0.74) + tower_t * 0.1
		return Color(b * rng.randf_range(0.82, 0.92), b * rng.randf_range(0.92, 1.0), b * rng.randf_range(1.0, 1.14))
	# Warm residential brick / stucco.
	var g := rng.randf_range(0.36, 0.64)
	return Color(g * rng.randf_range(1.0, 1.14), g * rng.randf_range(0.9, 1.02), g * rng.randf_range(0.78, 0.92))


# Number of placed settlements (0 if none / native extension absent).
func settlement_count() -> int:
	return settlement_centers.size()


# World-space position of city pad `i`'s centre (on the ground). The pad centres
# are stored in the planet's LOCAL frame and parented under `planet`, so the live
# world position follows the planet as it spins/orbits.
func settlement_world_pos(i: int) -> Vector3:
	if i < 0 or i >= settlement_centers.size() or planet == null:
		return Vector3.ZERO
	return planet.global_transform * settlement_centers[i]


func _build_moon() -> void:
	moon_system = Node3D.new()
	moon_system.name = "MoonSystem"
	add_child(moon_system)

	# Crater density — distinct seed so it doesn't pattern-match the planet's
	# noise. The CraterDensity samples a bowl-shaped profile for each impact
	# plus dust fbm for micro-relief.
	moon_density = CraterDensity.new(moon_radius, moon_seed, moon_crater_count)

	# Moon material — gray, mare/highland blend, no biomes.
	moon_material = ShaderMaterial.new()
	moon_material.shader = load("res://shaders/moon_terrain.gdshader")
	moon_material.set_shader_parameter("moon_radius", moon_radius)

	# Spawn the moon as a full LOD `Planet`. Inject the crater density BEFORE
	# add_child so Planet._ready() skips its default DensityField creation.
	moon = Planet.new()
	moon.name = "Moon"
	moon.planet_radius        = moon_radius
	moon.world_seed           = moon_seed
	moon.base_chunk_size      = moon_base_chunk_size
	moon.max_lod              = moon_max_lod
	moon.voxel_resolution     = 12
	moon.lod_factor           = 2.4
	moon.collision_lod_max    = 1
	moon.scatter_lod_max      = -1     # disable scatter (no grass / rocks on the moon)
	moon.enable_foliage       = false  # airless — no plants (also skips building the mesh)
	moon.sea_level_offset     = 0.0    # no ocean → no submersion test
	moon.terrain_material     = moon_material
	moon.set_density(moon_density)
	moon_system.add_child(moon)


func _apply_initial_transforms() -> void:
	# Spin axis: orbital-plane normal is +Y. Tilt by axial_tilt_deg around +X.
	_spin_axis_local = Basis(Vector3.RIGHT, deg_to_rad(axial_tilt_deg)) * Vector3.UP
	# The terrain shader's polar_axis is in OBJECT space — constant for the
	# life of the planet (it doesn't change as we orbit or spin).
	terrain_mat.set_shader_parameter("polar_axis", _spin_axis_local.normalized())
	# Hand the same axis to the rock-scatter material so its biome math
	# (latitude, polar caps, beach altitude) matches the terrain underneath.
	planet.set_scatter_axis(_spin_axis_local)
	# Water uses polar_axis as a stable reference for its tangent-frame
	# construction (the gradient sample directions on the sphere). Without
	# it the shader falls back to a view-dependent seed and seams across the
	# poles. Same constant object-space vector as terrain/rocks.
	water_mat.set_shader_parameter("polar_axis", _spin_axis_local.normalized())
	_update_transforms()


func absolute_planet_x() -> float:
	return orbit_radius * cos(_orbit_phase)


func absolute_planet_z() -> float:
	return orbit_radius * sin(_orbit_phase)


func _update_transforms() -> void:
	# Compute the absolute (cosmic-frame) planet position in 64-bit doubles,
	# then subtract the (also 64-bit) origin offset BEFORE collapsing to a
	# 32-bit-component Vector3. The subtraction cancels the huge AU-scale
	# magnitudes, leaving a small value that fits in float comfortably.
	var ax := absolute_planet_x() - _origin_offset_x
	var ay := 0.0 - _origin_offset_y
	var az := absolute_planet_z() - _origin_offset_z
	planet_system.global_position = Vector3(ax, ay, az)
	star.global_position = Vector3(-_origin_offset_x, -_origin_offset_y, -_origin_offset_z)

	# Axial rotation — independent of position, so unaffected by the offset.
	planet_system.transform.basis = Basis(_spin_axis_local.normalized(), _spin_phase)

	# Sun light: directional light points from the sun toward the planet. The
	# direction is just the unit vector between them, which is offset-invariant.
	var sun_to_planet := (planet_system.global_position - star.global_position).normalized()
	sun_light.look_at(star.global_position + sun_to_planet * 100.0, Vector3.UP)

	# Atmosphere & water shaders need world-space sun direction and planet
	# center. Both update to whatever the current floating-origin frame is.
	atmosphere_mat.set_shader_parameter("sun_direction", sun_to_planet)
	water_mat.set_shader_parameter("sun_direction", sun_to_planet)
	atmosphere_mat.set_shader_parameter("planet_center", planet_system.global_position)
	water_mat.set_shader_parameter("planet_center", planet_system.global_position)
	# Terrain aerial-perspective haze needs the same world-space sun + planet centre.
	if terrain_mat:
		terrain_mat.set_shader_parameter("sun_direction", sun_to_planet)
		terrain_mat.set_shader_parameter("planet_center", planet_system.global_position)
	if cloud_mat:
		cloud_mat.set_shader_parameter("sun_direction", sun_to_planet)
		cloud_mat.set_shader_parameter("planet_center", planet_system.global_position)
		# Inverse of the planet's spin rotation. The cloud shader rotates the
		# world-space sample position by this to get planet-LOCAL coords, so
		# the noise pattern stays locked to the surface as the planet spins
		# instead of whipping across the sky at the spin rate.
		cloud_mat.set_shader_parameter("planet_basis_inv", planet_system.transform.basis.inverse())

	# Moon — orbits the planet at moon_orbit_radius, inclined out of the
	# orbital plane by moon_inclination_deg. Computed in doubles so the
	# (planet_abs + moon_relative - offset) subtraction holds precision.
	var inc := deg_to_rad(moon_inclination_deg)
	var mx := absolute_planet_x() + moon_orbit_radius * cos(_moon_orbit_phase) - _origin_offset_x
	var my := 0.0 + moon_orbit_radius * sin(_moon_orbit_phase) * sin(inc) - _origin_offset_y
	var mz := absolute_planet_z() + moon_orbit_radius * sin(_moon_orbit_phase) * cos(inc) - _origin_offset_z
	moon_system.global_position = Vector3(mx, my, mz)
	moon.transform.basis = Basis(Vector3.UP, _moon_spin_phase)
